/* =====================================================================
   DỮ LIỆU CHƯƠNG TRÌNH – bám sát SGK Tiếng Anh Global Success (GDPT 2018)
   w = word · ipa · vi = nghĩa · vp = phiên âm cho phụ huynh · e = hình
   g = 1 -> từ chức năng (không dùng cho trò chơi đoán hình)
   ===================================================================== */
const THEMES = {
  friends: { name: "ME AND MY FRIENDS", vi: "Em và bạn bè", icon: "🧑‍🤝‍🧑" },
  school:  { name: "ME AND MY SCHOOL",  vi: "Em và trường học", icon: "🏫" },
  family:  { name: "ME AND MY FAMILY",  vi: "Em và gia đình", icon: "👨‍👩‍👧" },
  world:   { name: "ME AND THE WORLD AROUND", vi: "Em và thế giới quanh em", icon: "🌏" }
};

const G3 = [
{n:1,t:"Hello",vi:"Xin chào",th:"friends",e:"👋",
 comp:["Chào hỏi và tự giới thiệu","Đáp lời chào, cảm ơn và tạm biệt"],
 ph:[{k:"h",p:"s",w:"hello",s:"h"},{k:"b",p:"s",w:"bye",s:"b"}],
 words:[
  {w:"hello",ipa:"/həˈləʊ/",vi:"xin chào",vp:"hơ-lâu",e:"👋"},
  {w:"hi",ipa:"/haɪ/",vi:"chào",vp:"hai",e:"🙋"},
  {w:"bye",ipa:"/baɪ/",vi:"tạm biệt",vp:"bai",e:"🚶"},
  {w:"goodbye",ipa:"/ˌɡʊdˈbaɪ/",vi:"tạm biệt",vp:"gút-bai",e:"🚪"},
  {w:"fine",ipa:"/faɪn/",vi:"khoẻ, tốt",vp:"phai-n",e:"😊"},
  {w:"thank you",ipa:"/ˈθæŋk ju/",vi:"cảm ơn",vp:"thanh-kiu",e:"🙏"},
  {w:"how",ipa:"/haʊ/",vi:"như thế nào",vp:"hao",e:"🤔",g:1},
  {w:"you",ipa:"/ju/",vi:"bạn, các bạn",vp:"diu",e:"🧒",g:1},
  {w:"I",ipa:"/aɪ/",vi:"tôi, tớ",vp:"ai",e:"🙂",g:1}],
 pat:[["Hello. I'm Ben.","Hi, Ben. I'm Mai."],["How are you?","Fine, thank you."],["Goodbye, Mai.","Bye, Ben."]]},

{n:2,t:"Our names",vi:"Tên của chúng em",th:"friends",e:"📛",
 comp:["Hỏi và trả lời về tên của ai đó","Hỏi và trả lời về tuổi của ai đó"],
 ph:[{k:"m",p:"s",w:"Mary",s:"m"},{k:"n",p:"s",w:"Nam",s:"n"}],
 words:[
  {w:"name",ipa:"/neɪm/",vi:"tên",vp:"nêm",e:"📛"},
  {w:"old",ipa:"/əʊld/",vi:"tuổi, già, cũ",vp:"âu-lđ",e:"🎂"},
  {w:"my",ipa:"/maɪ/",vi:"của tôi",vp:"mai",e:"🙋",g:1},
  {w:"your",ipa:"/jɔː/",vi:"của bạn",vp:"do",e:"👉",g:1},
  {w:"what",ipa:"/wɒt/",vi:"cái gì",vp:"oát",e:"❓",g:1},
  {w:"how",ipa:"/haʊ/",vi:"như thế nào",vp:"hao",e:"🤔",g:1},
  {w:"eight",ipa:"/eɪt/",vi:"số tám (8)",vp:"ết",e:"8️⃣"},
  {w:"nine",ipa:"/naɪn/",vi:"số chín (9)",vp:"nai-n",e:"9️⃣"},
  {w:"ten",ipa:"/ten/",vi:"số mười (10)",vp:"te-n",e:"🔟"}],
 pat:[["What's your name?","My name's Mai."],["How old are you?","I'm eight years old."],["What's his name?","His name's Nam."]]},

{n:3,t:"Our friends",vi:"Các bạn của em",th:"friends",e:"🧑‍🤝‍🧑",
 comp:["Giới thiệu ai đó","Hỏi và trả lời về ai đó"],
 ph:[{k:"th",p:"s",w:"that",s:"ð"},{k:"th",p:"s",w:"thank",s:"θ"}],
 words:[
  {w:"friend",ipa:"/frend/",vi:"bạn, bạn bè",vp:"phren-đ",e:"🧑‍🤝‍🧑"},
  {w:"teacher",ipa:"/ˈtiːtʃə/",vi:"giáo viên",vp:"ti-chơ",e:"👩‍🏫"},
  {w:"Mr",ipa:"/ˈmɪstə/",vi:"ông, thầy",vp:"mít-tơ",e:"👨"},
  {w:"Ms",ipa:"/mɪz/",vi:"bà, cô",vp:"mi-z",e:"👩"},
  {w:"yes",ipa:"/jes/",vi:"vâng, đúng",vp:"dé-x",e:"✅"},
  {w:"no",ipa:"/nəʊ/",vi:"không",vp:"nâu",e:"❌"},
  {w:"this",ipa:"/ðɪs/",vi:"đây, cái này",vp:"đí-s",e:"👇",g:1},
  {w:"that",ipa:"/ðæt/",vi:"đó, kia",vp:"đát",e:"👉",g:1},
  {w:"it",ipa:"/ɪt/",vi:"nó, cái đó",vp:"ít",e:"🔵",g:1}],
 pat:[["This is Mai.","Hello, Mai."],["Is that Mr Long?","Yes, it is."],["Is this Ms Hoa?","No, it isn't. It's Ms Mai."]]},

{n:4,t:"Our bodies",vi:"Cơ thể của em",th:"friends",e:"🧒",
 comp:["Hỏi và trả lời về các bộ phận cơ thể","Đưa ra chỉ dẫn"],
 ph:[{k:"air",p:"i",w:"hair",s:"eə"},{k:"ear",p:"i",w:"ears",s:"ɪə"}],
 words:[
  {w:"ear",ipa:"/ɪə/",vi:"tai",vp:"i-ơ",e:"👂"},
  {w:"eye",ipa:"/aɪ/",vi:"mắt",vp:"ai",e:"👁️"},
  {w:"face",ipa:"/feɪs/",vi:"mặt",vp:"phêi-s",e:"😀"},
  {w:"hair",ipa:"/heə/",vi:"tóc",vp:"he-ơ",e:"💇"},
  {w:"hand",ipa:"/hænd/",vi:"bàn tay",vp:"hen-đ",e:"✋"},
  {w:"mouth",ipa:"/maʊθ/",vi:"miệng",vp:"mao-th",e:"👄"},
  {w:"nose",ipa:"/nəʊz/",vi:"mũi",vp:"nâu-z",e:"👃"},
  {w:"open",ipa:"/ˈəʊpən/",vi:"mở, há",vp:"âu-pừn",e:"👐"},
  {w:"touch",ipa:"/tʌtʃ/",vi:"chạm vào",vp:"tắch",e:"🤲"}],
 pat:[["What's this?","It's my nose."],["Touch your hair!","OK."],["Open your mouth!","Yes, Ms Hoa."]]},

{n:5,t:"My hobbies",vi:"Sở thích của em",th:"friends",e:"🎨",
 comp:["Hỏi và trả lời về sở thích của ai đó"],
 ph:[{k:"p",p:"s",w:"painting",s:"p"},{k:"r",p:"s",w:"running",s:"r"}],
 words:[
  {w:"cooking",ipa:"/ˈkʊkɪŋ/",vi:"nấu ăn",vp:"cúc-king",e:"🍳"},
  {w:"dancing",ipa:"/ˈdɑːnsɪŋ/",vi:"nhảy, múa",vp:"đan-xing",e:"💃"},
  {w:"drawing",ipa:"/ˈdrɔːɪŋ/",vi:"vẽ",vp:"đro-ing",e:"✏️"},
  {w:"painting",ipa:"/ˈpeɪntɪŋ/",vi:"tô vẽ",vp:"pên-ting",e:"🎨"},
  {w:"running",ipa:"/ˈrʌnɪŋ/",vi:"chạy",vp:"răn-ning",e:"🏃"},
  {w:"singing",ipa:"/ˈsɪŋɪŋ/",vi:"hát",vp:"xing-ing",e:"🎤"},
  {w:"swimming",ipa:"/ˈswɪmɪŋ/",vi:"bơi",vp:"xuim-ming",e:"🏊"},
  {w:"walking",ipa:"/ˈwɔːkɪŋ/",vi:"đi bộ",vp:"uóc-king",e:"🚶"},
  {w:"hobby",ipa:"/ˈhɒbi/",vi:"sở thích",vp:"hop-bi",e:"⭐"}],
 pat:[["What's your hobby?","It's singing."],["What's your hobby?","I like swimming."],["Is your hobby dancing?","Yes, it is."]]},

{n:6,t:"Our school",vi:"Trường của chúng em",th:"school",e:"🏫",
 comp:["Hỏi và trả lời về trường học của ai đó","Rủ đi đến một nơi ở trường và đồng ý"],
 ph:[{k:"pl",p:"s",w:"playground",s:"pl"},{k:"cl",p:"s",w:"classroom",s:"kl"}],
 words:[
  {w:"art room",ipa:"/ˈɑːt ruːm/",vi:"phòng mĩ thuật",vp:"át rum",e:"🎨"},
  {w:"classroom",ipa:"/ˈklɑːsruːm/",vi:"lớp học",vp:"cla-xrum",e:"🧑‍🏫"},
  {w:"computer room",ipa:"/kəmˈpjuːtə ruːm/",vi:"phòng tin học",vp:"cơm-piu-tơ rum",e:"💻"},
  {w:"gym",ipa:"/dʒɪm/",vi:"phòng thể chất",vp:"gim",e:"🤸"},
  {w:"library",ipa:"/ˈlaɪbrəri/",vi:"thư viện",vp:"lai-brơ-ri",e:"📚"},
  {w:"music room",ipa:"/ˈmjuːzɪk ruːm/",vi:"phòng âm nhạc",vp:"miu-zic rum",e:"🎵"},
  {w:"playground",ipa:"/ˈpleɪɡraʊnd/",vi:"sân chơi",vp:"plây-graon-đ",e:"🛝"},
  {w:"school",ipa:"/skuːl/",vi:"trường học",vp:"xcu-l",e:"🏫"}],
 pat:[["Is this our classroom?","Yes, it is."],["Let's go to the library.","OK, let's go."],["Is that the gym?","No, it isn't."]]},

{n:7,t:"Classroom instructions",vi:"Mệnh lệnh trong lớp",th:"school",e:"🙋",
 comp:["Đưa ra chỉ dẫn","Xin phép"],
 ph:[{k:"sp",p:"s",w:"speak",s:"sp"},{k:"st",p:"s",w:"stand",s:"st"}],
 words:[
  {w:"close",ipa:"/kləʊz/",vi:"đóng, gấp (sách)",vp:"clâu-z",e:"📕"},
  {w:"come in",ipa:"/kʌm ɪn/",vi:"đi vào",vp:"căm in",e:"🚪"},
  {w:"go out",ipa:"/ɡəʊ aʊt/",vi:"đi ra",vp:"gâu ao-t",e:"🚶"},
  {w:"sit down",ipa:"/sɪt daʊn/",vi:"ngồi xuống",vp:"xít đao-n",e:"🪑"},
  {w:"speak",ipa:"/spiːk/",vi:"nói",vp:"xpi-k",e:"🗣️"},
  {w:"stand up",ipa:"/stænd ʌp/",vi:"đứng lên",vp:"xten-đ ắp",e:"🧍"},
  {w:"open",ipa:"/ˈəʊpən/",vi:"mở",vp:"âu-pừn",e:"📖"},
  {w:"please",ipa:"/pliːz/",vi:"mời, xin mời",vp:"pli-z",e:"🙏"}],
 pat:[["Sit down, please!","Thank you."],["May I come in?","Yes, you can."],["May I go out?","No, you can't."]]},

{n:8,t:"My school things",vi:"Đồ dùng học tập",th:"school",e:"🎒",
 comp:["Nói về đồ dùng học tập mình có","Hỏi và trả lời về đồ dùng học tập"],
 ph:[{k:"oo",p:"i",w:"book",s:"ʊ"},{k:"a",p:"i",w:"eraser",s:"eɪ"}],
 words:[
  {w:"book",ipa:"/bʊk/",vi:"quyển sách",vp:"búc",e:"📕"},
  {w:"eraser",ipa:"/ɪˈreɪzə/",vi:"cục tẩy",vp:"i-rêi-zơ",e:"🧽"},
  {w:"notebook",ipa:"/ˈnəʊtbʊk/",vi:"vở viết",vp:"nâut-búc",e:"📓"},
  {w:"pen",ipa:"/pen/",vi:"bút mực",vp:"pe-n",e:"🖊️"},
  {w:"pencil",ipa:"/ˈpensl/",vi:"bút chì",vp:"pen-xồ",e:"✏️"},
  {w:"pencil case",ipa:"/ˈpensl keɪs/",vi:"hộp bút",vp:"pen-xồ kêi-s",e:"🧰"},
  {w:"ruler",ipa:"/ˈruːlə/",vi:"thước kẻ",vp:"ru-lơ",e:"📏"},
  {w:"school bag",ipa:"/ˈskuːl bæɡ/",vi:"cặp sách",vp:"xcu-l beg",e:"🎒"}],
 pat:[["I have a new pen.","It's nice!"],["Do you have a ruler?","Yes, I do."],["Do you have an eraser?","No, I don't."]]},

{n:9,t:"Colours",vi:"Màu sắc",th:"school",e:"🌈",
 comp:["Hỏi và trả lời về màu của một đồ vật","Hỏi và trả lời về màu của nhiều đồ vật"],
 ph:[{k:"bl",p:"s",w:"blue",s:"bl"},{k:"br",p:"s",w:"brown",s:"br"}],
 words:[
  {w:"black",ipa:"/blæk/",vi:"màu đen",vp:"blec",e:"⬛"},
  {w:"blue",ipa:"/bluː/",vi:"màu xanh da trời",vp:"blu",e:"🟦"},
  {w:"brown",ipa:"/braʊn/",vi:"màu nâu",vp:"brao-n",e:"🟫"},
  {w:"green",ipa:"/ɡriːn/",vi:"màu xanh lá cây",vp:"gri-n",e:"🟩"},
  {w:"orange",ipa:"/ˈɒrɪndʒ/",vi:"màu da cam",vp:"o-rin-giơ",e:"🟧"},
  {w:"red",ipa:"/red/",vi:"màu đỏ",vp:"rét",e:"🟥"},
  {w:"white",ipa:"/waɪt/",vi:"màu trắng",vp:"oai-t",e:"⬜"},
  {w:"yellow",ipa:"/ˈjeləʊ/",vi:"màu vàng",vp:"de-lâu",e:"🟨"},
  {w:"colour",ipa:"/ˈkʌlə/",vi:"màu sắc",vp:"ca-lơ",e:"🌈"},
  {w:"they",ipa:"/ðeɪ/",vi:"chúng, chúng nó",vp:"đêi",e:"👥",g:1}],
 pat:[["What colour is it?","It's red."],["What colour are they?","They're yellow."],["What colour is your school bag?","It's blue."]]},

{n:10,t:"Break time activities",vi:"Hoạt động giờ ra chơi",th:"school",e:"🔔",
 comp:["Nói về hoạt động giờ ra chơi","Hỏi và trả lời về hoạt động giờ ra chơi"],
 ph:[{k:"f",p:"s",w:"football",s:"f"},{k:"v",p:"s",w:"volleyball",s:"v"}],
 words:[
  {w:"break time",ipa:"/ˈbreɪk taɪm/",vi:"giờ ra chơi",vp:"brêi-k tai-m",e:"🔔"},
  {w:"chat",ipa:"/tʃæt/",vi:"nói chuyện",vp:"chát",e:"💬"},
  {w:"word puzzle",ipa:"/ˈwɜːd pʌzl/",vi:"trò chơi ô chữ",vp:"uơ-đ pa-zồ",e:"🧩"},
  {w:"badminton",ipa:"/ˈbædmɪntən/",vi:"cầu lông",vp:"bét-min-tơn",e:"🏸"},
  {w:"basketball",ipa:"/ˈbɑːskɪtbɔːl/",vi:"bóng rổ",vp:"ba-xkịt-bôl",e:"🏀"},
  {w:"chess",ipa:"/tʃes/",vi:"cờ",vp:"ché-x",e:"♟️"},
  {w:"football",ipa:"/ˈfʊtbɔːl/",vi:"bóng đá",vp:"phút-bôl",e:"⚽"},
  {w:"table tennis",ipa:"/ˈteɪbl tenɪs/",vi:"bóng bàn",vp:"tê-bồ ten-nít",e:"🏓"},
  {w:"volleyball",ipa:"/ˈvɒlibɔːl/",vi:"bóng chuyền",vp:"vo-li-bôl",e:"🏐"}],
 pat:[["What do you do at break time?","I play football."],["I chat with my friends at break time.","Me too."],["Do you play chess at break time?","Yes, I do."]]},

{n:11,t:"My family",vi:"Gia đình của em",th:"family",e:"👨‍👩‍👧",
 comp:["Hỏi và trả lời về thành viên gia đình","Hỏi và trả lời về tuổi của thành viên gia đình"],
 ph:[{k:"o",p:"i",w:"old",s:"əʊ"},{k:"ure",p:"i",w:"sure",s:"ʊə"}],
 words:[
  {w:"father",ipa:"/ˈfɑːðə/",vi:"bố",vp:"pha-đơ",e:"👨"},
  {w:"mother",ipa:"/ˈmʌðə/",vi:"mẹ",vp:"ma-đơ",e:"👩"},
  {w:"brother",ipa:"/ˈbrʌðə/",vi:"anh trai, em trai",vp:"bra-đơ",e:"👦"},
  {w:"sister",ipa:"/ˈsɪstə/",vi:"chị gái, em gái",vp:"xít-xtơ",e:"👧"},
  {w:"sure",ipa:"/ʃʊə/",vi:"chắc chắn",vp:"sua",e:"✔️"},
  {w:"eleven",ipa:"/ɪˈlevn/",vi:"số mười một (11)",vp:"i-le-vừn",e:"1️⃣1️⃣"},
  {w:"thirteen",ipa:"/ˌθɜːˈtiːn/",vi:"số mười ba (13)",vp:"thơ-ti-n",e:"1️⃣3️⃣"},
  {w:"fifteen",ipa:"/ˌfɪfˈtiːn/",vi:"số mười lăm (15)",vp:"phíp-ti-n",e:"1️⃣5️⃣"},
  {w:"twenty",ipa:"/ˈtwenti/",vi:"số hai mươi (20)",vp:"tuen-ti",e:"2️⃣0️⃣"}],
 pat:[["Who's this?","It's my mother."],["How old is he?","He's eleven."],["Who's that?","That's my father."]]},

{n:12,t:"Jobs",vi:"Nghề nghiệp",th:"family",e:"👩‍⚕️",
 comp:["Hỏi và trả lời về nghề nghiệp của thành viên gia đình"],
 ph:[{k:"er",p:"i",w:"mother",s:"ə"},{k:"or",p:"i",w:"doctor",s:"ə"}],
 words:[
  {w:"cook",ipa:"/kʊk/",vi:"đầu bếp",vp:"cúc",e:"👨‍🍳"},
  {w:"doctor",ipa:"/ˈdɒktə/",vi:"bác sĩ",vp:"đóc-tơ",e:"👨‍⚕️"},
  {w:"driver",ipa:"/ˈdraɪvə/",vi:"tài xế",vp:"đrai-vơ",e:"🚕"},
  {w:"farmer",ipa:"/ˈfɑːmə/",vi:"người nông dân",vp:"pha-mơ",e:"👨‍🌾"},
  {w:"nurse",ipa:"/nɜːs/",vi:"y tá",vp:"nơ-x",e:"👩‍⚕️"},
  {w:"singer",ipa:"/ˈsɪŋə/",vi:"ca sĩ",vp:"xing-ơ",e:"🎤"},
  {w:"teacher",ipa:"/ˈtiːtʃə/",vi:"giáo viên",vp:"ti-chơ",e:"👩‍🏫"},
  {w:"worker",ipa:"/ˈwɜːkə/",vi:"công nhân",vp:"uơ-cơ",e:"👷"},
  {w:"job",ipa:"/dʒɒb/",vi:"công việc",vp:"giop",e:"💼"}],
 pat:[["What's his job?","He's a doctor."],["Is she a nurse?","Yes, she is."],["What's her job?","She's a teacher."]]},

{n:13,t:"My house",vi:"Ngôi nhà của em",th:"family",e:"🏠",
 comp:["Hỏi và trả lời về vị trí các phòng trong nhà","Hỏi và trả lời về vị trí đồ vật trong phòng"],
 ph:[{k:"ou",p:"i",w:"house",s:"aʊ"},{k:"ow",p:"i",w:"brown",s:"aʊ"}],
 words:[
  {w:"house",ipa:"/haʊs/",vi:"ngôi nhà",vp:"hao-s",e:"🏠"},
  {w:"bathroom",ipa:"/ˈbɑːθruːm/",vi:"phòng tắm",vp:"ba-thrum",e:"🛁"},
  {w:"bedroom",ipa:"/ˈbedruːm/",vi:"phòng ngủ",vp:"bét-rum",e:"🛏️"},
  {w:"kitchen",ipa:"/ˈkɪtʃɪn/",vi:"phòng bếp",vp:"kít-chừn",e:"🍳"},
  {w:"living room",ipa:"/ˈlɪvɪŋ ruːm/",vi:"phòng khách",vp:"li-ving rum",e:"🛋️"},
  {w:"chair",ipa:"/tʃeə/",vi:"cái ghế",vp:"che-ơ",e:"🪑"},
  {w:"table",ipa:"/ˈteɪbl/",vi:"cái bàn",vp:"tê-bồ",e:"🍽️"},
  {w:"lamp",ipa:"/læmp/",vi:"cái đèn",vp:"lem-pơ",e:"💡"},
  {w:"here",ipa:"/hɪə/",vi:"ở đây",vp:"hi-ơ",e:"📍",g:1},
  {w:"there",ipa:"/ðeə/",vi:"ở kia",vp:"đe-ơ",e:"📌",g:1}],
 pat:[["Where's the lamp?","It's here."],["Where are the chairs?","They're there."],["Where's the kitchen?","It's there."]]},

{n:14,t:"My bedroom",vi:"Phòng ngủ của em",th:"family",e:"🛏️",
 comp:["Nói về số lượng đồ vật trong phòng","Miêu tả đồ vật trong phòng"],
 ph:[{k:"oo",p:"i",w:"room",s:"uː"},{k:"oo",p:"i",w:"door",s:"ɔː"}],
 words:[
  {w:"bed",ipa:"/bed/",vi:"cái giường",vp:"bét",e:"🛏️"},
  {w:"desk",ipa:"/desk/",vi:"cái bàn học",vp:"đé-xk",e:"🪑"},
  {w:"door",ipa:"/dɔː/",vi:"cửa ra vào",vp:"đo",e:"🚪"},
  {w:"window",ipa:"/ˈwɪndəʊ/",vi:"cửa sổ",vp:"uin-đâu",e:"🪟"},
  {w:"room",ipa:"/ruːm/",vi:"căn phòng",vp:"rum",e:"🏠"},
  {w:"big",ipa:"/bɪɡ/",vi:"to, lớn",vp:"bí-g",e:"🐘"},
  {w:"small",ipa:"/smɔːl/",vi:"nhỏ",vp:"xmô-l",e:"🐜"},
  {w:"new",ipa:"/njuː/",vi:"mới",vp:"niu",e:"✨"},
  {w:"old",ipa:"/əʊld/",vi:"cũ",vp:"âu-lđ",e:"📦"}],
 pat:[["There's a bed in the room.","It's big."],["The window is small.","Yes, it is."],["There are two chairs in the room.","They are new."]]},

{n:15,t:"At the dining table",vi:"Ở bàn ăn",th:"family",e:"🍽️",
 comp:["Mời và nhận hoặc từ chối đồ ăn, thức uống","Hỏi và trả lời về món ai đó muốn ăn/uống"],
 ph:[{k:"ea",p:"i",w:"bread",s:"e"},{k:"ea",p:"i",w:"meat",s:"iː"}],
 words:[
  {w:"bean",ipa:"/biːn/",vi:"đậu quả, hạt đậu",vp:"bi-n",e:"🌰"},
  {w:"bread",ipa:"/bred/",vi:"bánh mì",vp:"brét",e:"🍞"},
  {w:"chicken",ipa:"/ˈtʃɪkɪn/",vi:"thịt gà",vp:"chi-kừn",e:"🍗"},
  {w:"egg",ipa:"/eɡ/",vi:"trứng",vp:"éc",e:"🥚"},
  {w:"fish",ipa:"/fɪʃ/",vi:"cá",vp:"phí-sơ",e:"🐟"},
  {w:"juice",ipa:"/dʒuːs/",vi:"nước hoa quả",vp:"giu-s",e:"🧃"},
  {w:"meat",ipa:"/miːt/",vi:"thịt",vp:"mi-t",e:"🥩"},
  {w:"milk",ipa:"/mɪlk/",vi:"sữa",vp:"miu-k",e:"🥛"},
  {w:"rice",ipa:"/raɪs/",vi:"cơm",vp:"rai-s",e:"🍚"},
  {w:"water",ipa:"/ˈwɔːtə/",vi:"nước",vp:"uô-tơ",e:"💧"}],
 pat:[["Would you like some milk?","Yes, please."],["What would you like to eat?","I'd like some rice, please."],["Would you like some fish?","No, thanks."]]},

{n:16,t:"My pets",vi:"Thú cưng của em",th:"world",e:"🐶",
 comp:["Hỏi và trả lời về việc nuôi thú cưng","Hỏi và trả lời về số lượng thú cưng"],
 ph:[{k:"o",p:"i",w:"dog",s:"ɒ"},{k:"o",p:"i",w:"goldfish",s:"əʊ"}],
 words:[
  {w:"bird",ipa:"/bɜːd/",vi:"con chim",vp:"bơ-đ",e:"🐦"},
  {w:"cat",ipa:"/kæt/",vi:"con mèo",vp:"két",e:"🐱"},
  {w:"dog",ipa:"/dɒɡ/",vi:"con chó",vp:"đóc",e:"🐶"},
  {w:"goldfish",ipa:"/ˈɡəʊldfɪʃ/",vi:"con cá vàng",vp:"gâu-đờ-phí-sơ",e:"🐠"},
  {w:"parrot",ipa:"/ˈpærət/",vi:"con vẹt",vp:"pe-rợt",e:"🦜"},
  {w:"rabbit",ipa:"/ˈræbɪt/",vi:"con thỏ",vp:"re-bịt",e:"🐰"},
  {w:"many",ipa:"/ˈmeni/",vi:"nhiều",vp:"me-ni",e:"➕",g:1},
  {w:"some",ipa:"/sʌm/",vi:"một vài",vp:"xăm",e:"🔢",g:1}],
 pat:[["Do you have any pets?","Yes, I do. I have a cat."],["How many dogs do you have?","I have two dogs."],["Do you have any birds?","No, I don't."]]},

{n:17,t:"Our toys",vi:"Đồ chơi của chúng em",th:"world",e:"🧸",
 comp:["Nói về việc ai đó có đồ chơi gì"],
 ph:[{k:"i",p:"i",w:"kite",s:"aɪ"},{k:"oy",p:"i",w:"toy",s:"ɔɪ"}],
 words:[
  {w:"toy",ipa:"/tɔɪ/",vi:"đồ chơi",vp:"toi",e:"🧩"},
  {w:"bus",ipa:"/bʌs/",vi:"xe buýt",vp:"bá-x",e:"🚌"},
  {w:"car",ipa:"/kɑː/",vi:"xe ô tô",vp:"ca",e:"🚗"},
  {w:"kite",ipa:"/kaɪt/",vi:"cái diều",vp:"kai-t",e:"🪁"},
  {w:"plane",ipa:"/pleɪn/",vi:"máy bay",vp:"plê-n",e:"✈️"},
  {w:"ship",ipa:"/ʃɪp/",vi:"tàu thuỷ",vp:"síp",e:"🚢"},
  {w:"teddy bear",ipa:"/ˈtedi beə/",vi:"con gấu bông",vp:"te-đi be-ơ",e:"🧸"},
  {w:"train",ipa:"/treɪn/",vi:"tàu hoả",vp:"trê-n",e:"🚂"},
  {w:"truck",ipa:"/trʌk/",vi:"xe tải",vp:"trắc",e:"🚚"}],
 pat:[["He has a new kite.","It's beautiful."],["They have two teddy bears.","Lucky them!"],["She has a red car.","Nice!"]]},

{n:18,t:"Playing and doing",vi:"Em đang làm gì",th:"world",e:"🎬",
 comp:["Nói về việc ai đó đang làm","Hỏi và trả lời về việc ai đó đang làm"],
 ph:[{k:"n",p:"i",w:"listen",s:"n"},{k:"ng",p:"i",w:"singing",s:"ŋ"}],
 words:[
  {w:"reading",ipa:"/ˈriːdɪŋ/",vi:"đọc sách",vp:"ri-đing",e:"📖"},
  {w:"writing",ipa:"/ˈraɪtɪŋ/",vi:"viết",vp:"rai-ting",e:"✍️"},
  {w:"singing",ipa:"/ˈsɪŋɪŋ/",vi:"hát",vp:"xing-ing",e:"🎤"},
  {w:"dancing",ipa:"/ˈdɑːnsɪŋ/",vi:"nhảy múa",vp:"đan-xing",e:"💃"},
  {w:"watching TV",ipa:"/ˈwɒtʃɪŋ ˌtiːˈviː/",vi:"xem TV",vp:"oa-ching ti-vi",e:"📺"},
  {w:"drawing a picture",ipa:"/ˈdrɔːɪŋ ə ˈpɪktʃə/",vi:"vẽ tranh",vp:"đro-ing ơ pích-chơ",e:"🖼️"},
  {w:"listening to music",ipa:"/ˈlɪsnɪŋ tə ˈmjuːzɪk/",vi:"nghe nhạc",vp:"li-xừn-ing tu miu-zic",e:"🎧"},
  {w:"playing basketball",ipa:"/ˈpleɪɪŋ ˈbɑːskɪtbɔːl/",vi:"chơi bóng rổ",vp:"plêi-ing ba-xkịt-bôl",e:"🏀"}],
 pat:[["What are you doing?","I'm reading."],["I'm watching TV.","Me too."],["What are you doing?","I'm listening to music."]]},

{n:19,t:"Outdoor activities",vi:"Hoạt động ngoài trời",th:"world",e:"🪁",
 comp:["Nói về việc ai đó đang làm ngoài trời","Hỏi và trả lời về hoạt động ngoài trời"],
 ph:[{k:"pl",p:"s",w:"play",s:"pl"},{k:"fl",p:"s",w:"fly",s:"fl"}],
 words:[
  {w:"cycling",ipa:"/ˈsaɪklɪŋ/",vi:"đạp xe",vp:"xai-cờ-ling",e:"🚴"},
  {w:"flying a kite",ipa:"/ˈflaɪɪŋ ə kaɪt/",vi:"thả diều",vp:"phlai-ing ơ kai-t",e:"🪁"},
  {w:"painting",ipa:"/ˈpeɪntɪŋ/",vi:"vẽ tranh",vp:"pên-ting",e:"🎨"},
  {w:"playing badminton",ipa:"/ˈpleɪɪŋ ˈbædmɪntən/",vi:"chơi cầu lông",vp:"plêi-ing bét-min-tơn",e:"🏸"},
  {w:"running",ipa:"/ˈrʌnɪŋ/",vi:"chạy",vp:"răn-ning",e:"🏃"},
  {w:"skating",ipa:"/ˈskeɪtɪŋ/",vi:"trượt patanh",vp:"xkêi-ting",e:"⛸️"},
  {w:"skipping",ipa:"/ˈskɪpɪŋ/",vi:"nhảy dây",vp:"xkíp-ping",e:"🤸"},
  {w:"walking",ipa:"/ˈwɔːkɪŋ/",vi:"đi bộ",vp:"uóc-king",e:"🚶"}],
 pat:[["What's he doing?","He's cycling."],["What's she doing?","She's flying a kite."],["What are they doing?","They're skipping."]]},

{n:20,t:"At the zoo",vi:"Ở sở thú",th:"world",e:"🦁",
 comp:["Hỏi và trả lời về con vật nhìn thấy ở sở thú","Hỏi và trả lời về việc con vật đang làm"],
 ph:[{k:"a",p:"i",w:"parrot",s:"æ"},{k:"a",p:"i",w:"dancing",s:"ɑː"}],
 words:[
  {w:"elephant",ipa:"/ˈelɪfənt/",vi:"con voi",vp:"e-li-phừn",e:"🐘"},
  {w:"horse",ipa:"/hɔːs/",vi:"con ngựa",vp:"ho-s",e:"🐴"},
  {w:"monkey",ipa:"/ˈmʌŋki/",vi:"con khỉ",vp:"măng-ki",e:"🐵"},
  {w:"peacock",ipa:"/ˈpiːkɒk/",vi:"con công",vp:"pi-cóc",e:"🦚"},
  {w:"tiger",ipa:"/ˈtaɪɡə/",vi:"con hổ",vp:"tai-gơ",e:"🐯"},
  {w:"climbing",ipa:"/ˈklaɪmɪŋ/",vi:"leo, trèo",vp:"clai-ming",e:"🧗"},
  {w:"counting",ipa:"/ˈkaʊntɪŋ/",vi:"đếm",vp:"cao-n-ting",e:"🔢"},
  {w:"swinging",ipa:"/ˈswɪŋɪŋ/",vi:"đánh đu",vp:"xuing-ing",e:"🐒"}],
 pat:[["What can you see?","I can see a tiger."],["What's the monkey doing?","It's climbing."],["What can you see?","I can see two elephants."]]}
];

/* Bản đồ chương trình các lớp khác (dùng cho màn hình chọn lớp – sẽ mở dần) */
const GRADE_MAP = [
 {g:1,units:16,label:"Làm quen chữ cái & âm",em:"🐣",cls:"g1",ready:true,
  note:"16 Unit · chữ cái B, C, A, D… · câu đơn giản (Hi, I'm Bill.)"},
 {g:2,units:16,label:"Âm & mẫu câu ngắn",em:"🐤",cls:"g2",ready:true,
  note:"16 Unit · âm p, k, s, r… · câu hỏi Yes/No"},
 {g:3,units:20,label:"Bắt đầu 4 kĩ năng",em:"🦁",cls:"g3",ready:true,
  note:"20 Unit · 4 chủ điểm · Nghe – Nói – Đọc – Viết"},
 {g:4,units:20,label:"Mở rộng giao tiếp",em:"🐬",cls:"g4",ready:true,
  note:"20 Unit · thì quá khứ, chỉ đường, nghề nghiệp"},
 {g:5,units:20,label:"Chuẩn bị lên lớp 6",em:"🦅",cls:"g5",ready:true,
  note:"20 Unit · tương lai, sức khoẻ, du lịch, kể chuyện"}
];

/* ===== Bản dịch mẫu câu (cho khu vực phụ huynh) ===== */
const TRANS = {
"Hello. I'm Ben.":"Xin chào. Mình là Ben.",
"Hi, Ben. I'm Mai.":"Chào Ben. Mình là Mai.",
"How are you?":"Bạn có khoẻ không?",
"Fine, thank you.":"Mình khoẻ, cảm ơn bạn.",
"Goodbye, Mai.":"Tạm biệt Mai.",
"Bye, Ben.":"Tạm biệt Ben.",
"What's your name?":"Bạn tên là gì?",
"My name's Mai.":"Mình tên là Mai.",
"How old are you?":"Bạn bao nhiêu tuổi?",
"I'm eight years old.":"Mình tám tuổi.",
"What's his name?":"Bạn ấy tên là gì?",
"His name's Nam.":"Bạn ấy tên là Nam.",
"This is Mai.":"Đây là Mai.",
"Hello, Mai.":"Chào Mai.",
"Is that Mr Long?":"Kia là thầy Long phải không?",
"Yes, it is.":"Đúng vậy.",
"Is this Ms Hoa?":"Đây là cô Hoa phải không?",
"No, it isn't. It's Ms Mai.":"Không phải. Đó là cô Mai.",
"What's this?":"Đây là cái gì?",
"It's my nose.":"Đó là mũi của mình.",
"Touch your hair!":"Hãy chạm vào tóc của con!",
"OK.":"Vâng ạ.",
"Open your mouth!":"Hãy há miệng ra!",
"Yes, Ms Hoa.":"Vâng ạ, thưa cô Hoa.",
"What's your hobby?":"Sở thích của bạn là gì?",
"It's singing.":"Đó là ca hát.",
"I like swimming.":"Mình thích bơi.",
"Is your hobby dancing?":"Sở thích của bạn là nhảy múa phải không?",
"Is this our classroom?":"Đây là lớp học của chúng ta phải không?",
"Let's go to the library.":"Chúng mình đến thư viện nhé.",
"OK, let's go.":"Được, đi thôi.",
"Is that the gym?":"Kia là phòng thể chất phải không?",
"No, it isn't.":"Không phải.",
"Sit down, please!":"Mời em ngồi xuống!",
"Thank you.":"Em cảm ơn.",
"May I come in?":"Em vào lớp được không ạ?",
"Yes, you can.":"Được, em vào đi.",
"May I go out?":"Em ra ngoài được không ạ?",
"No, you can't.":"Không được.",
"I have a new pen.":"Mình có một cái bút mới.",
"It's nice!":"Đẹp quá!",
"Do you have a ruler?":"Bạn có thước kẻ không?",
"Yes, I do.":"Có, mình có.",
"Do you have an eraser?":"Bạn có cục tẩy không?",
"No, I don't.":"Không, mình không có.",
"What colour is it?":"Nó màu gì?",
"It's red.":"Nó màu đỏ.",
"What colour are they?":"Chúng màu gì?",
"They're yellow.":"Chúng màu vàng.",
"What colour is your school bag?":"Cặp sách của bạn màu gì?",
"It's blue.":"Nó màu xanh da trời.",
"What do you do at break time?":"Giờ ra chơi bạn làm gì?",
"I play football.":"Mình chơi bóng đá.",
"I chat with my friends at break time.":"Giờ ra chơi mình nói chuyện với các bạn.",
"Me too.":"Mình cũng vậy.",
"Do you play chess at break time?":"Giờ ra chơi bạn có chơi cờ không?",
"Who's this?":"Đây là ai?",
"It's my mother.":"Đó là mẹ mình.",
"How old is he?":"Anh ấy bao nhiêu tuổi?",
"He's eleven.":"Anh ấy mười một tuổi.",
"Who's that?":"Kia là ai?",
"That's my father.":"Đó là bố mình.",
"What's his job?":"Chú ấy làm nghề gì?",
"He's a doctor.":"Chú ấy là bác sĩ.",
"Is she a nurse?":"Cô ấy là y tá phải không?",
"Yes, she is.":"Đúng vậy.",
"What's her job?":"Cô ấy làm nghề gì?",
"She's a teacher.":"Cô ấy là giáo viên.",
"Where's the lamp?":"Cái đèn ở đâu?",
"It's here.":"Nó ở đây.",
"Where are the chairs?":"Những cái ghế ở đâu?",
"They're there.":"Chúng ở kia.",
"Where's the kitchen?":"Phòng bếp ở đâu?",
"It's there.":"Nó ở kia.",
"There's a bed in the room.":"Trong phòng có một cái giường.",
"It's big.":"Nó to.",
"The window is small.":"Cửa sổ thì nhỏ.",
"There are two chairs in the room.":"Trong phòng có hai cái ghế.",
"They are new.":"Chúng thì mới.",
"Would you like some milk?":"Con có muốn uống chút sữa không?",
"Yes, please.":"Dạ có ạ.",
"What would you like to eat?":"Con muốn ăn gì?",
"I'd like some rice, please.":"Con muốn ăn một ít cơm ạ.",
"Would you like some fish?":"Con có muốn ăn cá không?",
"No, thanks.":"Dạ thôi, con cảm ơn.",
"Do you have any pets?":"Bạn có nuôi thú cưng không?",
"Yes, I do. I have a cat.":"Có. Mình có một con mèo.",
"How many dogs do you have?":"Bạn có mấy con chó?",
"I have two dogs.":"Mình có hai con chó.",
"Do you have any birds?":"Bạn có nuôi chim không?",
"He has a new kite.":"Bạn ấy có một cái diều mới.",
"It's beautiful.":"Nó đẹp quá.",
"They have two teddy bears.":"Các bạn ấy có hai con gấu bông.",
"Lucky them!":"Các bạn ấy may quá!",
"She has a red car.":"Bạn ấy có một chiếc ô tô màu đỏ.",
"Nice!":"Tuyệt!",
"What are you doing?":"Bạn đang làm gì đấy?",
"I'm reading.":"Mình đang đọc sách.",
"I'm watching TV.":"Mình đang xem TV.",
"I'm listening to music.":"Mình đang nghe nhạc.",
"What's he doing?":"Bạn ấy đang làm gì?",
"He's cycling.":"Bạn ấy đang đạp xe.",
"What's she doing?":"Bạn ấy đang làm gì?",
"She's flying a kite.":"Bạn ấy đang thả diều.",
"What are they doing?":"Các bạn ấy đang làm gì?",
"They're skipping.":"Các bạn ấy đang nhảy dây.",
"What can you see?":"Bạn nhìn thấy con gì?",
"I can see a tiger.":"Mình nhìn thấy một con hổ.",
"What's the monkey doing?":"Con khỉ đang làm gì?",
"It's climbing.":"Nó đang leo trèo.",
"I can see two elephants.":"Mình nhìn thấy hai con voi."
};

/* ===== Phiên âm kiểu Việt cho các từ chức năng (giúp phụ huynh đọc) ===== */
const VP_EXTRA = {
"is":"iz","are":"a","am":"em","a":"ơ","an":"ơn","the":"đờ","this":"đí-s","that":"đát","that's":"đát-s",
"it":"ít","it's":"ít-s","i'm":"ai-m","he's":"hi-z","she's":"si-z","they're":"đe-ơ","there's":"đe-ơ-z",
"there":"đe-ơ","what's":"oát-s","who's":"hu-z","where's":"oe-ơ-z","how":"hao","old":"âu-lđ","years":"di-ơ-z",
"do":"đu","don't":"đôn-t","does":"đá-z","can":"ken","can't":"can-t","may":"mêi","let's":"lét-s","go":"gâu",
"to":"tu","ok":"âu-kêi","yes":"dét","no":"nâu","please":"pli-z","thanks":"thanh-x","would":"út","like":"lai-k",
"i'd":"ai-đ","eat":"i-t","drink":"đring-k","some":"xăm","any":"e-ni","have":"heo","has":"hé-z","see":"xi",
"doing":"đu-ing","at":"ét","with":"uít","me":"mi","too":"tu","my":"mai","your":"do","his":"hi-z","her":"hơ",
"our":"ao-ơ","two":"tu","new":"niu","nice":"nai-s","beautiful":"biu-ti-phun","lucky":"lắc-ki","them":"đem",
"play":"plêi","isn't":"i-zừn-t","aren't":"a-n-t","in":"in","on":"on","not":"nót","eight":"ết","name's":"nêm-z",
"i":"ai","you":"diu","he":"hi","she":"si","they":"đây","we":"uy","and":"en","of":"ợv","for":"pho","this?":"đí-s",
"mr":"mít-tơ","ms":"mi-z","ben":"ben","mai":"mai","nam":"nam","long":"long","hoa":"hoa","tv":"ti-vi",
"lucy":"lu-xi","minh":"minh","linh":"linh","bill":"bin","mary":"me-ri","music":"miu-zic","friends":"phren-z",
"time":"tai-m","break":"brêi-k","hobby":"hop-bi","dogs":"đóc-s","pets":"pét-s","bears":"be-ơ-z","elephants":"e-li-phừn-s",
"chairs":"che-ơ-z","reading":"ri-đing","cycling":"xai-cờ-ling","skipping":"xkíp-ping","climbing":"clai-ming",
"watching":"oa-ching","listening":"li-xừn-ing","flying":"phlai-ing","singing":"xing-ing","dancing":"đan-xing",
"swimming":"xuim-ming","eleven":"i-le-vừn","red":"rét","blue":"blu","yellow":"de-lâu","big":"bích","small":"xmô-l",
"thank":"thanh","sit":"xít","down":"đao-n","come":"căm","out":"ao-t","bag":"beg","where":"oe-ơ","teddy":"te-đi",
"school":"xcu-l","pencil":"pen-xồ","case":"kêi-s","word":"uơ-đ","puzzle":"pa-zồ","table":"tê-bồ","tennis":"ten-nít",
"living":"li-ving","art":"át","computer":"cơm-piu-tơ","picture":"pích-chơ","goodbye,":"gút-bai","colour":"ca-lơ",
"years":"di-ơ-z","name":"nêm","hair":"he-ơ","mouth":"mao-th","nose":"nâu-z","open":"âu-pừn","touch":"tắch",
"library":"lai-brơ-ri","gym":"gim","classroom":"cla-xrum","ruler":"ru-lơ","eraser":"i-rêi-zơ","lamp":"lem-pơ",
"chairs":"che-ơ-z","kitchen":"kít-chừn","bed":"bét","window":"uin-đâu","milk":"miu-k","rice":"rai-s","fish":"phí-sơ",
"cat":"két","dog":"đóc","dogs":"đóc-s","birds":"bơ-đ-z","kite":"kai-t","car":"ca","monkey":"măng-ki","tiger":"tai-gơ",
"mother":"ma-đơ","father":"pha-đơ","doctor":"đóc-tơ","nurse":"nơ-x","teacher":"ti-chơ","job":"giop","football":"phút-bôl",
"chess":"chét","hobby's":"hop-bi-z","singing":"xing-ing","swimming":"xuim-ming","reading":"ri-đing","music":"miu-zic"
};

/* =====================================================================
   LỚP 1 – Tiếng Anh 1 Global Success (Làm quen tiếng Anh, GDPT 2018)
   16 Unit · mỗi Unit 1 chữ cái · 3–4 từ · 1 mẫu câu
   letter.pos = "s" (âm đầu, phụ âm) | "i" (nguyên âm nằm trong từ)
   ===================================================================== */
const G1 = [
{n:1,t:"In the school playground",vi:"Ở sân trường",e:"⚽",
 letter:{U:"B",l:"b",name:"bee",vp:"bờ",pos:"s"},
 words:[
  {w:"ball",ipa:"/bɔːl/",vi:"quả bóng",vp:"bôl",e:"⚽"},
  {w:"bike",ipa:"/baɪk/",vi:"xe đạp",vp:"bai-k",e:"🚲"},
  {w:"book",ipa:"/bʊk/",vi:"quyển sách",vp:"búc",e:"📕"}],
 pat:[["Hi, I'm Bill.","Hi, Bill."],["Bye, Bill.","Bye."]]},

{n:2,t:"In the dining room",vi:"Trong phòng ăn",e:"🍽️",
 letter:{U:"C",l:"c",name:"see",vp:"cờ",pos:"s"},
 words:[
  {w:"cake",ipa:"/keɪk/",vi:"bánh ngọt",vp:"kêi-k",e:"🎂"},
  {w:"car",ipa:"/kɑː/",vi:"xe ô tô",vp:"ca",e:"🚗"},
  {w:"cat",ipa:"/kæt/",vi:"con mèo",vp:"két",e:"🐱"},
  {w:"cup",ipa:"/kʌp/",vi:"cái cốc",vp:"cắp",e:"☕"}],
 frame:{t:"I have a {w}.",vi:"Mình có một {v}.",words:["cake","car","cat","cup"]},
 pat:[["I have a car.","Nice!"]]},

{n:3,t:"At the street market",vi:"Ở chợ",e:"🧺",
 letter:{U:"A",l:"a",name:"ay",vp:"a",pos:"i"},
 words:[
  {w:"apple",ipa:"/ˈæpl/",vi:"quả táo",vp:"áp-pồ",e:"🍎"},
  {w:"bag",ipa:"/bæɡ/",vi:"cái túi",vp:"beg",e:"🎒"},
  {w:"can",ipa:"/kæn/",vi:"lon nước",vp:"ken",e:"🥫"},
  {w:"hat",ipa:"/hæt/",vi:"cái mũ",vp:"hé-đ",e:"🎩"}],
 frame:{t:"This is my {w}.",vi:"Đây là {v} của mình.",words:["apple","bag","can","hat"]},
 pat:[["This is my bag.","Oh, nice bag!"]]},

{n:4,t:"In the bedroom",vi:"Trong phòng ngủ",e:"🛏️",
 letter:{U:"D",l:"d",name:"dee",vp:"đờ",pos:"s"},
 words:[
  {w:"desk",ipa:"/desk/",vi:"bàn học",vp:"đé-xk",e:"🪑"},
  {w:"dog",ipa:"/dɒɡ/",vi:"con chó",vp:"đóc",e:"🐶"},
  {w:"door",ipa:"/dɔː/",vi:"cái cửa",vp:"đo",e:"🚪"},
  {w:"duck",ipa:"/dʌk/",vi:"con vịt",vp:"đắc",e:"🦆"}],
 frame:{t:"This is a {w}.",vi:"Đây là {v}.",words:["desk","dog","door","duck"]},
 pat:[["This is a dog.","Wow!"]]},

{n:5,t:"At the fish and chip shop",vi:"Ở quán cá và khoai chiên",e:"🍟",
 letter:{U:"I",l:"i",name:"eye",vp:"i",pos:"i"},
 words:[
  {w:"chicken",ipa:"/ˈtʃɪkɪn/",vi:"thịt gà",vp:"chi-kừn",e:"🍗"},
  {w:"chips",ipa:"/tʃɪps/",vi:"khoai tây chiên",vp:"chíp-s",e:"🍟"},
  {w:"fish",ipa:"/fɪʃ/",vi:"cá",vp:"phí-sơ",e:"🐟"},
  {w:"milk",ipa:"/mɪlk/",vi:"sữa",vp:"miu-k",e:"🥛"}],
 frame:{t:"I like {w}.",vi:"Mình thích {v}.",words:["chicken","chips","fish","milk"]},
 pat:[["I like milk.","Me too."]]},

{n:6,t:"In the classroom",vi:"Trong lớp học",e:"🏫",
 letter:{U:"E",l:"e",name:"ee",vp:"e",pos:"i"},
 words:[
  {w:"bell",ipa:"/bel/",vi:"cái chuông",vp:"beo",e:"🔔"},
  {w:"pen",ipa:"/pen/",vi:"cái bút",vp:"pe-n",e:"🖊️"},
  {w:"pencil",ipa:"/ˈpensl/",vi:"bút chì",vp:"pen-xồ",e:"✏️"},
  {w:"red",ipa:"/red/",vi:"màu đỏ",vp:"rét",e:"🟥"}],
 frame:{t:"It's a red {w}.",vi:"Đó là {v} màu đỏ.",words:["bell","pen","pencil"]},
 pat:[["It's a red pen.","Yes!"]]},

{n:7,t:"In the garden",vi:"Trong khu vườn",e:"🌷",
 letter:{U:"G",l:"g",name:"gee",vp:"gờ",pos:"s"},
 words:[
  {w:"garden",ipa:"/ˈɡɑːdn/",vi:"khu vườn",vp:"ga-đừn",e:"🌷"},
  {w:"gate",ipa:"/ɡeɪt/",vi:"cái cổng",vp:"gêi-t",e:"🚧"},
  {w:"girl",ipa:"/ɡɜːl/",vi:"bé gái",vp:"gơ-l",e:"👧"},
  {w:"goat",ipa:"/ɡəʊt/",vi:"con dê",vp:"gâu-t",e:"🐐"}],
 frame:{t:"There's a {w}.",vi:"Có một {v}.",words:["garden","gate","girl","goat"]},
 pat:[["There's a garden.","It's beautiful."]]},

{n:8,t:"In the park",vi:"Ở công viên",e:"🌳",
 letter:{U:"H",l:"h",name:"aitch",vp:"hờ",pos:"s"},
 words:[
  {w:"hair",ipa:"/heə/",vi:"tóc",vp:"he-ơ",e:"💇"},
  {w:"hand",ipa:"/hænd/",vi:"bàn tay",vp:"hen-đ",e:"✋"},
  {w:"head",ipa:"/hed/",vi:"cái đầu",vp:"hé-đ",e:"🙆"},
  {w:"horse",ipa:"/hɔːs/",vi:"con ngựa",vp:"ho-s",e:"🐴"}],
 frame:{t:"Touch your {w}.",vi:"Hãy chạm vào {v} của con.",words:["hair","hand","head"]},
 pat:[["Touch your hair.","OK."]]},

{n:9,t:"In the shop",vi:"Trong cửa hàng",e:"🏪",
 letter:{U:"O",l:"o",name:"oh",vp:"o",pos:"i"},
 words:[
  {w:"clock",ipa:"/klɒk/",vi:"đồng hồ",vp:"clóc",e:"🕐",pl:"clocks"},
  {w:"lock",ipa:"/lɒk/",vi:"ổ khoá",vp:"lóc",e:"🔒",pl:"locks"},
  {w:"mop",ipa:"/mɒp/",vi:"cây lau nhà",vp:"móp",e:"🧹",pl:"mops"},
  {w:"pot",ipa:"/pɒt/",vi:"cái nồi",vp:"pót",e:"🍲",pl:"pots"}],
 frame:{t:"How many {p}?",vi:"Có bao nhiêu {v}?",words:["clock","lock","mop","pot"],plural:true},
 pat:[["How many clocks?","Two."]]},

{n:10,t:"At the zoo",vi:"Ở sở thú",e:"🦁",
 letter:{U:"M",l:"m",name:"em",vp:"mờ",pos:"s"},
 words:[
  {w:"mango",ipa:"/ˈmæŋɡəʊ/",vi:"quả xoài",vp:"meng-gâu",e:"🥭"},
  {w:"monkey",ipa:"/ˈmʌŋki/",vi:"con khỉ",vp:"măng-ki",e:"🐵"},
  {w:"mother",ipa:"/ˈmʌðə/",vi:"mẹ",vp:"ma-đơ",e:"👩"},
  {w:"mouse",ipa:"/maʊs/",vi:"con chuột",vp:"mao-s",e:"🐭"}],
 frame:{t:"That's a {w}.",vi:"Kia là {v}.",words:["mango","monkey","mouse"]},
 pat:[["That's a monkey.","Yes, it is."]]},

{n:11,t:"At the bus stop",vi:"Ở bến xe buýt",e:"🚌",
 letter:{U:"U",l:"u",name:"you",vp:"â",pos:"i"},
 words:[
  {w:"bus",ipa:"/bʌs/",vi:"xe buýt",vp:"bá-x",e:"🚌"},
  {w:"run",ipa:"/rʌn/",vi:"chạy",vp:"răn",e:"🏃"},
  {w:"sun",ipa:"/sʌn/",vi:"mặt trời",vp:"xăn",e:"☀️"},
  {w:"truck",ipa:"/trʌk/",vi:"xe tải",vp:"trắc",e:"🚚"}],
 frame:{t:"It's a {w}.",vi:"Đó là {v}.",words:["bus","sun","truck"]},
 pat:[["She's running.","He's running."]]},

{n:12,t:"At the lake",vi:"Bên hồ nước",e:"🏞️",
 letter:{U:"L",l:"l",name:"el",vp:"lờ",pos:"s"},
 words:[
  {w:"lake",ipa:"/leɪk/",vi:"cái hồ",vp:"lêi-k",e:"🏞️"},
  {w:"leaf",ipa:"/liːf/",vi:"chiếc lá",vp:"li-phơ",e:"🍃"},
  {w:"lemon",ipa:"/ˈlemən/",vi:"quả chanh",vp:"le-mừn",e:"🍋",pl:"lemons"}],
 frame:{t:"Look at the {p}.",vi:"Hãy nhìn {v} kìa.",words:["lemon","leaf","lake"],plural:true},
 pat:[["Look at the lemons.","Wow!"]]},

{n:13,t:"In the school canteen",vi:"Ở căng tin trường",e:"🍜",
 letter:{U:"N",l:"n",name:"en",vp:"nờ",pos:"i"},
 words:[
  {w:"banana",ipa:"/bəˈnɑːnə/",vi:"quả chuối",vp:"bơ-na-nơ",e:"🍌",pl:"bananas"},
  {w:"noodles",ipa:"/ˈnuːdlz/",vi:"mì",vp:"nu-đồ-z",e:"🍜"},
  {w:"nuts",ipa:"/nʌts/",vi:"các loại hạt",vp:"nát-s",e:"🥜"}],
 frame:{t:"She's having {w}.",vi:"Bạn ấy đang ăn {v}.",words:["noodles","nuts"]},
 pat:[["She's having noodles.","Yummy!"]]},

{n:14,t:"In the toy shop",vi:"Trong cửa hàng đồ chơi",e:"🧸",
 letter:{U:"T",l:"t",name:"tee",vp:"tờ",pos:"s"},
 words:[
  {w:"teddy bear",ipa:"/ˈtedi beə/",vi:"gấu bông",vp:"te-đi be-ơ",e:"🧸"},
  {w:"tiger",ipa:"/ˈtaɪɡə/",vi:"con hổ",vp:"tai-gơ",e:"🐯"},
  {w:"top",ipa:"/tɒp/",vi:"con quay",vp:"tóp",e:"🌀"},
  {w:"turtle",ipa:"/ˈtɜːtl/",vi:"con rùa",vp:"tơ-tồ",e:"🐢"}],
 frame:{t:"I can see a {w}.",vi:"Mình nhìn thấy {v}.",words:["teddy bear","tiger","top","turtle"]},
 pat:[["I can see a tiger.","Me too."]]},

{n:15,t:"At the football match",vi:"Ở trận bóng đá",e:"⚽",
 letter:{U:"F",l:"f",name:"ef",vp:"phờ",pos:"s"},
 words:[
  {w:"face",ipa:"/feɪs/",vi:"khuôn mặt",vp:"phêi-s",e:"😀"},
  {w:"father",ipa:"/ˈfɑːðə/",vi:"bố",vp:"pha-đơ",e:"👨"},
  {w:"foot",ipa:"/fʊt/",vi:"bàn chân",vp:"phút",e:"🦶"},
  {w:"football",ipa:"/ˈfʊtbɔːl/",vi:"bóng đá",vp:"phút-bôl",e:"⚽"}],
 frame:{t:"Point to your {w}.",vi:"Hãy chỉ vào {v} của con.",words:["face","foot"]},
 pat:[["Point to your hand.","OK."]]},

{n:16,t:"At home",vi:"Ở nhà",e:"🏠",
 letter:{U:"W",l:"w",name:"double-you",vp:"u-ờ",pos:"s"},
 words:[
  {w:"wash",ipa:"/wɒʃ/",vi:"rửa",vp:"oó-sơ",e:"🧼"},
  {w:"water",ipa:"/ˈwɔːtə/",vi:"nước",vp:"uô-tơ",e:"💧"},
  {w:"window",ipa:"/ˈwɪndəʊ/",vi:"cửa sổ",vp:"uin-đâu",e:"🪟",pl:"windows"}],
 frame:{t:"How many {p} can you see?",vi:"Con nhìn thấy bao nhiêu {v}?",words:["window"],plural:true},
 pat:[["How many windows can you see?","I can see six."]]}
];

/* nhóm bài theo 4 chặng ôn tập của SGK lớp 1 */
const G1_GROUPS = [
 {label:"Chặng 1 · Review 1",vi:"Unit 1–4 · chữ B, C, A, D",icon:"🅰️",units:[1,2,3,4]},
 {label:"Chặng 2 · Review 2",vi:"Unit 5–8 · chữ I, E, G, H",icon:"🅱️",units:[5,6,7,8]},
 {label:"Chặng 3 · Review 3",vi:"Unit 9–12 · chữ O, M, U, L",icon:"🔡",units:[9,10,11,12]},
 {label:"Chặng 4 · Review 4",vi:"Unit 13–16 · chữ N, T, F, W",icon:"🔠",units:[13,14,15,16]}
];

/* bản dịch mẫu câu lớp 1 */
Object.assign(TRANS, {
"Hi, I'm Bill.":"Chào, mình là Bill.",
"Hi, Bill.":"Chào Bill.",
"Bye, Bill.":"Tạm biệt Bill.",
"Bye.":"Tạm biệt.",
"I have a car.":"Mình có một chiếc ô tô.",
"Nice!":"Đẹp quá!",
"This is my bag.":"Đây là cái túi của mình.",
"Oh, nice bag!":"Ồ, cái túi đẹp quá!",
"This is a dog.":"Đây là một con chó.",
"Wow!":"Ồ!",
"I like milk.":"Mình thích sữa.",
"Me too.":"Mình cũng vậy.",
"It's a red pen.":"Đó là một cái bút màu đỏ.",
"Yes!":"Đúng rồi!",
"There's a garden.":"Có một khu vườn.",
"It's beautiful.":"Đẹp quá.",
"Touch your hair.":"Hãy chạm vào tóc của con.",
"OK.":"Vâng ạ.",
"How many clocks?":"Có bao nhiêu cái đồng hồ?",
"Two.":"Hai cái.",
"That's a monkey.":"Kia là một con khỉ.",
"Yes, it is.":"Đúng vậy.",
"She's running.":"Bạn ấy đang chạy.",
"He's running.":"Bạn ấy đang chạy.",
"Look at the lemons.":"Hãy nhìn những quả chanh kìa.",
"She's having noodles.":"Bạn ấy đang ăn mì.",
"Yummy!":"Ngon quá!",
"I can see a tiger.":"Mình nhìn thấy một con hổ.",
"Point to your hand.":"Hãy chỉ vào bàn tay của con.",
"How many windows can you see?":"Con nhìn thấy bao nhiêu cửa sổ?",
"I can see six.":"Con nhìn thấy sáu cái."
});

/* =====================================================================
   LỚP 2 – Tiếng Anh 2 Global Success (Làm quen tiếng Anh, GDPT 2018)
   16 Unit · mỗi Unit 1 âm/chữ · 3–4 từ · 1 mẫu câu
   Lớp 2 đã bắt đầu ĐỌC và VIẾT từ ngắn → có thêm dạng đọc từ, gõ chính tả
   ===================================================================== */
const G2 = [
{n:1,t:"At my birthday party",vi:"Ở bữa tiệc sinh nhật của em",e:"🎂",
 letter:{U:"P",l:"p",name:"pee",vp:"pờ",pos:"s"},
 words:[
  {w:"pasta",ipa:"/ˈpæstə/",vi:"mì Ý",vp:"pa-xtơ",e:"🍝"},
  {w:"popcorn",ipa:"/ˈpɒpkɔːn/",vi:"bỏng ngô",vp:"póp-con",e:"🍿"},
  {w:"pizza",ipa:"/ˈpiːtsə/",vi:"bánh pizza",vp:"pít-xơ",e:"🍕"}],
 frame:{t:"The {w} is yummy.",vi:"{v} ngon quá.",words:["pasta","popcorn","pizza"]},
 pat:[["The popcorn is yummy.","Yes, it is."]]},

{n:2,t:"In the backyard",vi:"Ở sân sau",e:"🌳",
 letter:{U:"K",l:"k",name:"kay",vp:"cờ",pos:"i"},
 words:[
  {w:"kite",ipa:"/kaɪt/",vi:"cái diều",vp:"kai-t",e:"🪁"},
  {w:"bike",ipa:"/baɪk/",vi:"xe đạp",vp:"bai-k",e:"🚲"},
  {w:"kitten",ipa:"/ˈkɪtn/",vi:"mèo con",vp:"kít-từn",e:"🐈"}],
 pat:[["Is she flying a kite?","Yes, she is."],["Is he riding a bike?","No, he isn't."]]},

{n:3,t:"At the seaside",vi:"Ở bờ biển",e:"🏖️",
 letter:{U:"S",l:"s",name:"ess",vp:"xờ",pos:"s"},
 words:[
  {w:"sail",ipa:"/seɪl/",vi:"cánh buồm",vp:"xêi-l",e:"⛵"},
  {w:"sand",ipa:"/sænd/",vi:"cát",vp:"xen-đ",e:"🏖️"},
  {w:"sea",ipa:"/siː/",vi:"biển",vp:"xi",e:"🌊"}],
 frame:{t:"Let's look at the {w}!",vi:"Chúng mình cùng ngắm {v} nào!",words:["sail","sand","sea"]},
 pat:[["Let's look at the sea!","OK."]]},

{n:4,t:"In the countryside",vi:"Ở vùng quê",e:"🌄",
 letter:{U:"R",l:"r",name:"ar",vp:"rờ",pos:"s"},
 words:[
  {w:"rainbow",ipa:"/ˈreɪnbəʊ/",vi:"cầu vồng",vp:"rêin-bâu",e:"🌈"},
  {w:"river",ipa:"/ˈrɪvə/",vi:"dòng sông",vp:"ri-vơ",e:"🏞️"},
  {w:"road",ipa:"/rəʊd/",vi:"con đường",vp:"râu-đ",e:"🛣️"}],
 frame:{t:"I can see a {w}.",vi:"Mình nhìn thấy {v}.",words:["rainbow","river","road"]},
 pat:[["What can you see?","I can see a rainbow."]]},

{n:5,t:"In the classroom",vi:"Trong lớp học",e:"🏫",
 letter:{U:"Q",l:"q",name:"cue",vp:"quờ",pos:"i"},
 words:[
  {w:"question",ipa:"/ˈkwestʃən/",vi:"câu hỏi",vp:"quét-chừn",e:"❓"},
  {w:"square",ipa:"/skweə/",vi:"hình vuông",vp:"xquê-ơ",e:"⬜"},
  {w:"quiz",ipa:"/kwɪz/",vi:"bài kiểm tra nhanh",vp:"quí-z",e:"📝"}],
 frame:{t:"He's doing a {w}.",vi:"Bạn ấy đang làm {v}.",words:["quiz"]},
 pat:[["What's he doing?","He's doing a quiz."]]},

{n:6,t:"On the farm",vi:"Ở nông trại",e:"🚜",
 letter:{U:"X",l:"x",name:"ex",vp:"c-xờ",pos:"i"},
 words:[
  {w:"box",ipa:"/bɒks/",vi:"cái hộp",vp:"bóc-s",e:"📦"},
  {w:"fox",ipa:"/fɒks/",vi:"con cáo",vp:"phóc-s",e:"🦊"},
  {w:"ox",ipa:"/ɒks/",vi:"con bò",vp:"óc-s",e:"🐂"}],
 frame:{t:"Is there a {w}?",vi:"Có {v} ở đó không?",words:["box","fox","ox"]},
 pat:[["Is there a fox?","Yes, there is."],["Is there an ox?","No, there isn't."]]},

{n:7,t:"In the kitchen",vi:"Trong phòng bếp",e:"🍳",
 letter:{U:"J",l:"j",name:"jay",vp:"giờ",pos:"s"},
 words:[
  {w:"juice",ipa:"/dʒuːs/",vi:"nước ép",vp:"giu-s",e:"🧃"},
  {w:"jelly",ipa:"/ˈdʒeli/",vi:"thạch",vp:"gie-li",e:"🍮"},
  {w:"jam",ipa:"/dʒæm/",vi:"mứt",vp:"giem",e:"🍯"}],
 frame:{t:"Pass me the {w}, please.",vi:"Làm ơn đưa mình {v}.",words:["juice","jelly","jam"]},
 pat:[["Pass me the jam, please.","Here you are."]]},

{n:8,t:"In the village",vi:"Trong ngôi làng",e:"🏘️",
 letter:{U:"V",l:"v",name:"vee",vp:"vờ",pos:"s"},
 words:[
  {w:"village",ipa:"/ˈvɪlɪdʒ/",vi:"ngôi làng",vp:"vi-lịch",e:"🏘️"},
  {w:"van",ipa:"/væn/",vi:"xe tải nhỏ",vp:"ven",e:"🚐"},
  {w:"volleyball",ipa:"/ˈvɒlibɔːl/",vi:"bóng chuyền",vp:"vo-li-bôl",e:"🏐"}],
 frame:{t:"Can you draw a {w}?",vi:"Bạn vẽ được {v} không?",words:["village","van","volleyball"]},
 pat:[["Can you draw a van?","Yes, I can."],["Can you draw a village?","No, I can't."]]},

{n:9,t:"In the grocery store",vi:"Trong cửa hàng tạp hoá",e:"🛒",
 letter:{U:"Y",l:"y",name:"why",vp:"dờ",pos:"s"},
 words:[
  {w:"yogurt",ipa:"/ˈjɒɡət/",vi:"sữa chua",vp:"dô-gợt",e:"🥛"},
  {w:"yams",ipa:"/jæmz/",vi:"củ khoai mỡ",vp:"dem-z",e:"🍠"},
  {w:"yo-yo",ipa:"/ˈjəʊjəʊ/",vi:"con quay yo-yo",vp:"dâu-dâu",e:"🪀",pl:"yo-yos"}],
 frame:{t:"I want some {w}.",vi:"Mình muốn một ít {v}.",words:["yogurt","yams"]},
 pat:[["What do you want?","I want some yams."]]},

{n:10,t:"At the zoo",vi:"Ở sở thú",e:"🦓",
 letter:{U:"Z",l:"z",name:"zed",vp:"dờ (rung)",pos:"s"},
 words:[
  {w:"zoo",ipa:"/zuː/",vi:"sở thú",vp:"zu",e:"🦁"},
  {w:"zebu",ipa:"/ˈziːbuː/",vi:"bò u",vp:"zi-bu",e:"🐄"},
  {w:"zebra",ipa:"/ˈzebrə/",vi:"ngựa vằn",vp:"ze-brơ",e:"🦓"}],
 frame:{t:"Do you like the {w}?",vi:"Bạn có thích {v} không?",words:["zoo","zebu","zebra"]},
 pat:[["Do you like the zoo?","Yes, I do."],["Do you like the zebu?","No, I don't."]]},

{n:11,t:"In the playground",vi:"Ở sân chơi",e:"🛝",
 letter:{U:"I",l:"i",name:"eye",vp:"i",pos:"i"},
 words:[
  {w:"sliding",ipa:"/ˈslaɪdɪŋ/",vi:"trượt cầu trượt",vp:"xlai-đing",e:"🛝"},
  {w:"riding",ipa:"/ˈraɪdɪŋ/",vi:"đạp xe, cưỡi",vp:"rai-đing",e:"🚴"},
  {w:"driving",ipa:"/ˈdraɪvɪŋ/",vi:"lái xe",vp:"đrai-ving",e:"🚗"}],
 frame:{t:"They're {w}.",vi:"Các bạn ấy đang {v}.",words:["sliding","riding","driving"]},
 pat:[["They're driving cars.","Wow!"]]},

{n:12,t:"At the café",vi:"Ở quán cà phê",e:"☕",
 letter:{U:"A",l:"a",name:"ay",vp:"a",pos:"i"},
 words:[
  {w:"grapes",ipa:"/ɡreɪps/",vi:"chùm nho",vp:"grêi-p-s",e:"🍇",many:true},
  {w:"cake",ipa:"/keɪk/",vi:"bánh ngọt",vp:"kêi-k",e:"🎂"},
  {w:"table",ipa:"/ˈteɪbl/",vi:"cái bàn",vp:"tê-bồ",e:"🍽️"}],
 frame:{t:"The {w} {be} on the table.",vi:"{v} ở trên bàn.",words:["grapes","cake"]},
 pat:[["The cake is on the table.","Yummy!"],["The grapes are on the table.","I like grapes."]]},

{n:13,t:"In the maths class",vi:"Trong giờ Toán",e:"🔢",
 letter:{U:"N",l:"n",name:"en",vp:"nờ",pos:"i"},
 words:[
  {w:"eleven",ipa:"/ɪˈlevn/",vi:"số mười một (11)",vp:"i-le-vừn",e:"1️⃣1️⃣"},
  {w:"thirteen",ipa:"/ˌθɜːˈtiːn/",vi:"số mười ba (13)",vp:"thơ-ti-n",e:"1️⃣3️⃣"},
  {w:"fourteen",ipa:"/ˌfɔːˈtiːn/",vi:"số mười bốn (14)",vp:"pho-ti-n",e:"1️⃣4️⃣"},
  {w:"fifteen",ipa:"/ˌfɪfˈtiːn/",vi:"số mười lăm (15)",vp:"phíp-ti-n",e:"1️⃣5️⃣"},
  {w:"number",ipa:"/ˈnʌmbə/",vi:"con số",vp:"năm-bơ",e:"🔢"}],
 frame:{t:"It's {w}.",vi:"Đó là {v}.",words:["eleven","thirteen","fourteen","fifteen"]},
 pat:[["What number is it?","It's eleven."]]},

{n:14,t:"At home",vi:"Ở nhà",e:"👨‍👩‍👧",
 letter:{U:"Er",l:"er",name:"er",vp:"ơ (cuối từ)",pos:"i"},
 words:[
  {w:"brother",ipa:"/ˈbrʌðə/",vi:"anh trai, em trai",vp:"bra-đơ",e:"👦"},
  {w:"sister",ipa:"/ˈsɪstə/",vi:"chị gái, em gái",vp:"xít-xtơ",e:"👧"},
  {w:"grandmother",ipa:"/ˈɡrænmʌðə/",vi:"bà",vp:"gren-ma-đơ",e:"👵"}],
 frame:{t:"How old is your {w}?",vi:"{v} của bạn bao nhiêu tuổi?",words:["brother","sister","grandmother"]},
 pat:[["How old is your brother?","He's nineteen."]]},

{n:15,t:"In the clothes shop",vi:"Trong cửa hàng quần áo",e:"👕",
 letter:{U:"Sh",l:"sh",name:"esh",vp:"sờ",pos:"s"},
 words:[
  {w:"shirts",ipa:"/ʃɜːts/",vi:"áo sơ mi",vp:"sơ-t-s",e:"👕"},
  {w:"shoes",ipa:"/ʃuːz/",vi:"giày",vp:"su-z",e:"👟"},
  {w:"shorts",ipa:"/ʃɔːts/",vi:"quần đùi",vp:"sót-s",e:"🩳"}],
 frame:{t:"Where are the {w}?",vi:"{v} ở đâu?",words:["shirts","shoes","shorts"]},
 pat:[["Where are the shoes?","Over there."]]},

{n:16,t:"At the campsite",vi:"Ở khu cắm trại",e:"⛺",
 letter:{U:"T",l:"t",name:"tee",vp:"tờ",pos:"i"},
 words:[
  {w:"tent",ipa:"/tent/",vi:"cái lều",vp:"ten-t",e:"⛺"},
  {w:"teapot",ipa:"/ˈtiːpɒt/",vi:"ấm trà",vp:"ti-pót",e:"🫖"},
  {w:"blanket",ipa:"/ˈblæŋkɪt/",vi:"cái chăn",vp:"bleng-kịt",e:"🛏️"}],
 frame:{t:"Is the blanket near the {w}?",vi:"Cái chăn có ở gần {v} không?",words:["tent","teapot"]},
 pat:[["Is the blanket near the tent?","No, it isn't. It's in the tent."]]}
];

const G2_GROUPS = [
 {label:"Chặng 1 · Review 1",vi:"Unit 1–4 · âm p, k, s, r",icon:"🅿️",units:[1,2,3,4]},
 {label:"Chặng 2 · Review 2",vi:"Unit 5–8 · âm q, x, j, v",icon:"🔠",units:[5,6,7,8]},
 {label:"Chặng 3 · Review 3",vi:"Unit 9–12 · âm y, z, i, a",icon:"🔡",units:[9,10,11,12]},
 {label:"Chặng 4 · Review 4",vi:"Unit 13–16 · âm n, er, sh, t",icon:"🔤",units:[13,14,15,16]}
];

Object.assign(TRANS, {
"The popcorn is yummy.":"Bỏng ngô ngon quá.",
"Yes, it is.":"Đúng vậy.",
"Is she flying a kite?":"Bạn ấy đang thả diều phải không?",
"Yes, she is.":"Đúng vậy.",
"Is he riding a bike?":"Bạn ấy đang đạp xe phải không?",
"No, he isn't.":"Không phải.",
"Let's look at the sea!":"Chúng mình cùng ngắm biển nào!",
"OK.":"Được thôi.",
"What can you see?":"Bạn nhìn thấy gì?",
"I can see a rainbow.":"Mình nhìn thấy một cầu vồng.",
"What's he doing?":"Bạn ấy đang làm gì?",
"He's doing a quiz.":"Bạn ấy đang làm bài kiểm tra nhanh.",
"Is there a fox?":"Có con cáo nào ở đó không?",
"Yes, there is.":"Có.",
"Is there an ox?":"Có con bò nào ở đó không?",
"No, there isn't.":"Không có.",
"Pass me the jam, please.":"Làm ơn đưa mình lọ mứt.",
"Here you are.":"Của bạn đây.",
"Can you draw a van?":"Bạn vẽ được xe tải nhỏ không?",
"Yes, I can.":"Được, mình vẽ được.",
"Can you draw a village?":"Bạn vẽ được ngôi làng không?",
"No, I can't.":"Không, mình không vẽ được.",
"What do you want?":"Bạn muốn gì?",
"I want some yams.":"Mình muốn một ít khoai mỡ.",
"Do you like the zoo?":"Bạn có thích sở thú không?",
"Yes, I do.":"Có, mình thích.",
"Do you like the zebu?":"Bạn có thích con bò u không?",
"No, I don't.":"Không, mình không thích.",
"They're driving cars.":"Các bạn ấy đang lái ô tô.",
"Wow!":"Ồ!",
"The cake is on the table.":"Cái bánh ở trên bàn.",
"Yummy!":"Ngon quá!",
"The grapes are on the table.":"Chùm nho ở trên bàn.",
"I like grapes.":"Mình thích nho.",
"What number is it?":"Đó là số mấy?",
"It's eleven.":"Đó là số mười một.",
"How old is your brother?":"Anh trai bạn bao nhiêu tuổi?",
"He's nineteen.":"Anh ấy mười chín tuổi.",
"Where are the shoes?":"Đôi giày ở đâu?",
"Over there.":"Ở đằng kia.",
"Is the blanket near the tent?":"Cái chăn có ở gần lều không?",
"No, it isn't. It's in the tent.":"Không. Nó ở trong lều."
});
