/* =====================================================================
   LỚP 4 – Tiếng Anh 4 Global Success (GDPT 2018) · 20 Unit · 4 chủ điểm
   st = âm tiết mang trọng âm (dùng cho trò "Trọng âm")
   focus = cột Phonics / Word stress của Book Map
   ===================================================================== */
const G4 = [
{n:1,t:"My friends",vi:"Bạn bè của em",th:"friends",e:"🌏",
 comp:["Hỏi và trả lời về nơi mình đến từ","Hỏi và trả lời về nơi ai đó đến từ"],
 focus:{label:"Phonics",items:["America","Australia"]},
 words:[
  {w:"Viet Nam",ipa:"/ˌvjetˈnɑːm/",vi:"Việt Nam",vp:"vi-ệt nam",e:"🇻🇳",st:2},
  {w:"America",ipa:"/əˈmerɪkə/",vi:"nước Mỹ",vp:"ơ-me-ri-cơ",e:"🇺🇸",st:2},
  {w:"Australia",ipa:"/ɒˈstreɪliə/",vi:"nước Úc",vp:"ót-xtrêi-li-ơ",e:"🇦🇺",st:2},
  {w:"Britain",ipa:"/ˈbrɪtn/",vi:"nước Anh (gồm Anh, Xcốt-len và Uên)",vp:"bri-tần",e:"🇬🇧",st:1},
  {w:"Japan",ipa:"/dʒəˈpæn/",vi:"Nhật Bản",vp:"giơ-pen",e:"🇯🇵",st:2},
  {w:"Malaysia",ipa:"/məˈleɪziə/",vi:"Ma-lai-xi-a",vp:"mơ-lêi-zi-ơ",e:"🇲🇾",st:2},
  {w:"Singapore",ipa:"/ˌsɪŋəˈpɔː/",vi:"Xin-ga-po",vp:"xing-ơ-po",e:"🇸🇬",st:3},
  {w:"Thailand",ipa:"/ˈtaɪlænd/",vi:"Thái Lan",vp:"thai-len",e:"🇹🇭",st:1}],
 pat:[["Where are you from?","I'm from Viet Nam."],["Where's he from?","He's from Japan."],["Where's she from?","She's from Australia."]]},

{n:2,t:"Time and daily routines",vi:"Giờ giấc và việc hằng ngày",th:"friends",e:"⏰",
 comp:["Hỏi và nói giờ","Hỏi và trả lời về sinh hoạt hằng ngày"],
 focus:{label:"Phonics",items:["get","bed"]},
 words:[
  {w:"o'clock",ipa:"/əˈklɒk/",vi:"giờ đúng",vp:"ơ-clóc",e:"🕐",st:2},
  {w:"fifteen",ipa:"/ˌfɪfˈtiːn/",vi:"mười lăm phút",vp:"phíp-ti-n",e:"1️⃣5️⃣",st:2},
  {w:"thirty",ipa:"/ˈθɜːti/",vi:"ba mươi phút",vp:"thơ-ti",e:"3️⃣0️⃣",st:1},
  {w:"forty-five",ipa:"/ˌfɔːti ˈfaɪv/",vi:"bốn mươi lăm phút",vp:"pho-ti phai-v",e:"4️⃣5️⃣"},
  {w:"get up",ipa:"/ˌɡet ˈʌp/",vi:"thức dậy",vp:"ghét ắp",e:"🛏️"},
  {w:"have breakfast",ipa:"/hæv ˈbrekfəst/",vi:"ăn sáng",vp:"heo brếch-phợt",e:"🍳"},
  {w:"go to school",ipa:"/ɡəʊ tə skuːl/",vi:"đi học",vp:"gâu tu xcu-l",e:"🎒"},
  {w:"go to bed",ipa:"/ɡəʊ tə bed/",vi:"đi ngủ",vp:"gâu tu bét",e:"😴"}],
 pat:[["What time is it?","It's six o'clock."],["What time do you get up?","I get up at six."],["What time do you go to bed?","I go to bed at nine thirty."]]},

{n:3,t:"My week",vi:"Một tuần của em",th:"friends",e:"📅",
 comp:["Hỏi và trả lời về các ngày trong tuần","Hỏi và trả lời về việc làm trong các ngày"],
 focus:{label:"Phonics",items:["music","Sunday"]},
 words:[
  {w:"Monday",ipa:"/ˈmʌndeɪ/",vi:"thứ Hai",vp:"măn-đêi",e:"2️⃣",st:1},
  {w:"Tuesday",ipa:"/ˈtjuːzdeɪ/",vi:"thứ Ba",vp:"tiu-z-đêi",e:"3️⃣",st:1},
  {w:"Wednesday",ipa:"/ˈwenzdeɪ/",vi:"thứ Tư",vp:"quen-z-đêi",e:"4️⃣",st:1},
  {w:"Thursday",ipa:"/ˈθɜːzdeɪ/",vi:"thứ Năm",vp:"thơ-z-đêi",e:"5️⃣",st:1},
  {w:"Friday",ipa:"/ˈfraɪdeɪ/",vi:"thứ Sáu",vp:"phrai-đêi",e:"6️⃣",st:1},
  {w:"Saturday",ipa:"/ˈsætədeɪ/",vi:"thứ Bảy",vp:"xe-tơ-đêi",e:"7️⃣",st:1},
  {w:"Sunday",ipa:"/ˈsʌndeɪ/",vi:"Chủ nhật",vp:"xăn-đêi",e:"🌞",st:1},
  {w:"do housework",ipa:"/duː ˈhaʊswɜːk/",vi:"làm việc nhà",vp:"đu hao-x-uơ-c",e:"🧹"},
  {w:"listen to music",ipa:"/ˈlɪsn tə ˈmjuːzɪk/",vi:"nghe nhạc",vp:"li-xừn tu miu-zic",e:"🎧"},
  {w:"study at school",ipa:"/ˈstʌdi ət skuːl/",vi:"học ở trường",vp:"xta-đi ét xcu-l",e:"📚"}],
 pat:[["What day is it today?","It's Monday."],["What do you do on Sundays?","I listen to music."],["What do you do on Saturdays?","I do housework."]]},

{n:4,t:"My birthday party",vi:"Tiệc sinh nhật của em",th:"friends",e:"🎂",
 comp:["Hỏi và trả lời về sinh nhật","Hỏi và trả lời về món muốn ăn/uống"],
 focus:{label:"Phonics",items:["jam","water"]},
 words:[
  {w:"January",ipa:"/ˈdʒænjuəri/",vi:"tháng Một",vp:"gien-diu-ơ-ri",e:"⛄",st:1},
  {w:"February",ipa:"/ˈfebruəri/",vi:"tháng Hai",vp:"phép-ru-ơ-ri",e:"🧧",st:1},
  {w:"March",ipa:"/mɑːtʃ/",vi:"tháng Ba",vp:"mách",e:"🌸"},
  {w:"April",ipa:"/ˈeɪprəl/",vi:"tháng Tư",vp:"êi-prồ",e:"🌱",st:1},
  {w:"birthday",ipa:"/ˈbɜːθdeɪ/",vi:"sinh nhật",vp:"bơth-đêi",e:"🎂",st:1},
  {w:"party",ipa:"/ˈpɑːti/",vi:"bữa tiệc",vp:"pa-ti",e:"🎉",st:1},
  {w:"lemonade",ipa:"/ˌleməˈneɪd/",vi:"nước chanh",vp:"le-mơ-nêi-đ",e:"🥤",st:3},
  {w:"grapes",ipa:"/ɡreɪps/",vi:"nho",vp:"grêi-p-s",e:"🍇"},
  {w:"chips",ipa:"/tʃɪps/",vi:"khoai tây chiên",vp:"chíp-s",e:"🍟"},
  {w:"jam",ipa:"/dʒæm/",vi:"mứt",vp:"giem",e:"🍯"},
  {w:"juice",ipa:"/dʒuːs/",vi:"nước ép",vp:"giu-s",e:"🧃"},
  {w:"water",ipa:"/ˈwɔːtə/",vi:"nước",vp:"uô-tơ",e:"💧",st:1}],
 pat:[["When's your birthday?","It's in April."],["What do you want to eat?","I want some chips."],["What do you want to drink?","I want some lemonade."]]},

{n:5,t:"Things we can do",vi:"Những việc chúng em làm được",th:"friends",e:"🎸",
 comp:["Hỏi và trả lời về khả năng của ai đó","Nói về việc làm được và chưa làm được"],
 focus:{label:"Phonics",items:["yes","no"]},
 words:[
  {w:"cook",ipa:"/kʊk/",vi:"nấu ăn",vp:"cúc",e:"👨‍🍳"},
  {w:"draw",ipa:"/drɔː/",vi:"vẽ",vp:"đro",e:"🎨"},
  {w:"swim",ipa:"/swɪm/",vi:"bơi",vp:"xuim",e:"🏊"},
  {w:"play the guitar",ipa:"/pleɪ ðə ɡɪˈtɑː/",vi:"chơi đàn ghi-ta",vp:"plêi đờ ghi-ta",e:"🎸"},
  {w:"play the piano",ipa:"/pleɪ ðə piˈænəʊ/",vi:"chơi đàn piano",vp:"plêi đờ pi-e-nâu",e:"🎹"},
  {w:"ride a bike",ipa:"/raɪd ə baɪk/",vi:"đi xe đạp",vp:"rai-đ ơ bai-k",e:"🚲"},
  {w:"ride a horse",ipa:"/raɪd ə hɔːs/",vi:"cưỡi ngựa",vp:"rai-đ ơ ho-s",e:"🐴"},
  {w:"roller skate",ipa:"/ˈrəʊlə skeɪt/",vi:"trượt patanh",vp:"râu-lơ xkêi-t",e:"⛸️"}],
 pat:[["Can you swim?","Yes, I can."],["Can he ride a horse?","No, he can't, but he can ride a bike."],["Can she play the piano?","Yes, she can."]]},

{n:6,t:"Our school facilities",vi:"Cơ sở vật chất trường em",th:"school",e:"🏫",
 comp:["Hỏi và trả lời về vị trí của trường","Hỏi và trả lời về số lượng phòng ốc"],
 focus:{label:"Phonics",items:["mountains","villages"]},
 words:[
  {w:"city",ipa:"/ˈsɪti/",vi:"thành phố",vp:"xi-ti",e:"🏙️",st:1},
  {w:"town",ipa:"/taʊn/",vi:"thị trấn",vp:"tao-n",e:"🏘️"},
  {w:"village",ipa:"/ˈvɪlɪdʒ/",vi:"ngôi làng",vp:"vi-lịch",e:"🏡",st:1},
  {w:"mountains",ipa:"/ˈmaʊntɪnz/",vi:"những dãy núi",vp:"mao-n-tần-z",e:"⛰️",st:1},
  {w:"building",ipa:"/ˈbɪldɪŋ/",vi:"toà nhà",vp:"biu-đing",e:"🏢",st:1},
  {w:"computer room",ipa:"/kəmˈpjuːtə ruːm/",vi:"phòng máy tính",vp:"cơm-piu-tơ rum",e:"💻"},
  {w:"garden",ipa:"/ˈɡɑːdn/",vi:"khu vườn",vp:"ga-đừn",e:"🌷",st:1},
  {w:"playground",ipa:"/ˈpleɪɡraʊnd/",vi:"sân chơi",vp:"plêi-grao-n-đ",e:"🛝",st:1}],
 pat:[["Where's your school?","It's in the city."],["How many buildings are there at your school?","There are three."],["How many computer rooms are there?","There is one."]]},

{n:7,t:"Our timetables",vi:"Thời khoá biểu của chúng em",th:"school",e:"📋",
 comp:["Hỏi và trả lời về các môn học","Hỏi và trả lời về thời khoá biểu"],
 focus:{label:"Phonics",items:["Vietnamese","science"]},
 words:[
  {w:"art",ipa:"/ɑːt/",vi:"môn Mĩ thuật",vp:"át",e:"🎨"},
  {w:"English",ipa:"/ˈɪŋɡlɪʃ/",vi:"môn Tiếng Anh",vp:"ing-lịch",e:"🔤",st:1},
  {w:"maths",ipa:"/mæθs/",vi:"môn Toán",vp:"mét-th",e:"➗"},
  {w:"music",ipa:"/ˈmjuːzɪk/",vi:"môn Âm nhạc",vp:"miu-zic",e:"🎵",st:1},
  {w:"science",ipa:"/ˈsaɪəns/",vi:"môn Khoa học",vp:"xai-ừn-s",e:"🔬",st:1},
  {w:"Vietnamese",ipa:"/ˌvjetnəˈmiːz/",vi:"môn Tiếng Việt",vp:"vi-ệt-nơ-mi-z",e:"🇻🇳",st:3},
  {w:"history and geography",ipa:"/ˈhɪstri ənd dʒiˈɒɡrəfi/",vi:"môn Lịch sử và Địa lí",vp:"hít-x-tri en gi-ó-grơ-phi",e:"🗺️"},
  {w:"timetable",ipa:"/ˈtaɪmteɪbl/",vi:"thời khoá biểu",vp:"tai-m-tê-bồ",e:"📋",st:1}],
 pat:[["What subjects do you have today?","I have maths and English."],["When do you have music?","I have it on Monday."],["When do you have science?","I have it on Friday."]]},

{n:8,t:"My favourite subjects",vi:"Môn học em yêu thích",th:"school",e:"⭐",
 comp:["Hỏi và trả lời về môn học yêu thích","Hỏi và nêu lí do thích một môn học"],
 focus:{label:"Phonics",items:["like","write"]},
 words:[
  {w:"favourite",ipa:"/ˈfeɪvərɪt/",vi:"yêu thích",vp:"phêi-vơ-rịt",e:"⭐",st:1},
  {w:"IT",ipa:"/ˌaɪ ˈtiː/",vi:"môn Tin học",vp:"ai ti",e:"💻"},
  {w:"PE",ipa:"/ˌpiː ˈiː/",vi:"môn Thể dục",vp:"pi i",e:"🤸"},
  {w:"painter",ipa:"/ˈpeɪntə/",vi:"hoạ sĩ",vp:"pên-tơ",e:"🖌️",st:1},
  {w:"English teacher",ipa:"/ˈɪŋɡlɪʃ ˈtiːtʃə/",vi:"giáo viên Tiếng Anh",vp:"ing-lịch ti-chơ",e:"👩‍🏫"},
  {w:"maths teacher",ipa:"/mæθs ˈtiːtʃə/",vi:"giáo viên Toán",vp:"mét-th ti-chơ",e:"👨‍🏫"},
  {w:"because",ipa:"/bɪˈkɒz/",vi:"bởi vì",vp:"bi-cóz",e:"💬",st:2},
  {w:"why",ipa:"/waɪ/",vi:"tại sao",vp:"oai",e:"❓"}],
 pat:[["What's your favourite subject?","It's maths."],["Why do you like maths?","Because I want to be a maths teacher."],["Why do you like art?","Because I want to be a painter."]]},

{n:9,t:"Our sports day",vi:"Ngày hội thể thao",th:"school",e:"🏃",
 comp:["Hỏi và trả lời về ngày hội thể thao","Hỏi và trả lời về thời gian diễn ra"],
 focus:{label:"Phonics",items:["February","July"]},
 words:[
  {w:"May",ipa:"/meɪ/",vi:"tháng Năm",vp:"mêi",e:"🌺"},
  {w:"June",ipa:"/dʒuːn/",vi:"tháng Sáu",vp:"giu-n",e:"🏖️"},
  {w:"July",ipa:"/dʒuˈlaɪ/",vi:"tháng Bảy",vp:"giu-lai",e:"☀️",st:2},
  {w:"August",ipa:"/ˈɔːɡəst/",vi:"tháng Tám",vp:"ô-gợt",e:"🌻",st:1},
  {w:"September",ipa:"/sepˈtembə/",vi:"tháng Chín",vp:"xép-tem-bơ",e:"🎒",st:2},
  {w:"October",ipa:"/ɒkˈtəʊbə/",vi:"tháng Mười",vp:"óc-tâu-bơ",e:"🍂",st:2},
  {w:"November",ipa:"/nəʊˈvembə/",vi:"tháng Mười một",vp:"nâu-vem-bơ",e:"🌧️",st:2},
  {w:"December",ipa:"/dɪˈsembə/",vi:"tháng Mười hai",vp:"đi-xem-bơ",e:"🎄",st:2},
  {w:"sports day",ipa:"/ˈspɔːts deɪ/",vi:"ngày hội thể thao",vp:"xpo-t-s đêi",e:"🏃"}],
 pat:[["Is your sports day in May?","Yes, it is."],["When's your sports day?","It's in December."],["Is your sports day in July?","No, it isn't. It's in October."]]},

{n:10,t:"Our summer holidays",vi:"Kì nghỉ hè của chúng em",th:"school",e:"🏖️",
 comp:["Hỏi và trả lời về việc ai đó đã ở đâu","Hỏi và trả lời về nơi đã đến mùa hè trước"],
 focus:{label:"Phonics",items:["were","where"]},
 words:[
  {w:"beach",ipa:"/biːtʃ/",vi:"bãi biển",vp:"bí-g",e:"🏖️"},
  {w:"campsite",ipa:"/ˈkæmpsaɪt/",vi:"khu cắm trại",vp:"kem-p-xai-t",e:"⛺",st:1},
  {w:"countryside",ipa:"/ˈkʌntrisaɪd/",vi:"vùng quê",vp:"căn-tri-xai-đ",e:"🌄",st:1},
  {w:"Bangkok",ipa:"/ˌbæŋˈkɒk/",vi:"Băng Cốc",vp:"beng-cóc",e:"🇹🇭",st:2},
  {w:"London",ipa:"/ˈlʌndən/",vi:"Luân Đôn",vp:"lăn-đừn",e:"🇬🇧",st:1},
  {w:"Sydney",ipa:"/ˈsɪdni/",vi:"Xít-ni",vp:"xít-ni",e:"🇦🇺",st:1},
  {w:"Tokyo",ipa:"/ˈtəʊkiəʊ/",vi:"Tô-ki-ô",vp:"tâu-ki-âu",e:"🇯🇵",st:1},
  {w:"yesterday",ipa:"/ˈjestədeɪ/",vi:"hôm qua",vp:"de-x-tơ-đêi",e:"📆",st:1}],
 pat:[["Were you at the beach last weekend?","Yes, I was."],["Where were you last summer?","I was in London."],["Were you in Tokyo last summer?","No, I wasn't."]]},

{n:11,t:"My home",vi:"Ngôi nhà của em",th:"family",e:"🏠",
 comp:["Hỏi và trả lời về nơi ai đó sống","Hỏi và trả lời về đặc điểm một nơi"],
 focus:{label:"Phonics",items:["big","street"]},
 words:[
  {w:"road",ipa:"/rəʊd/",vi:"con đường",vp:"râu-đ",e:"🛣️"},
  {w:"street",ipa:"/striːt/",vi:"phố",vp:"xtri-t",e:"🏙️"},
  {w:"live",ipa:"/lɪv/",vi:"sống, ở",vp:"li-v",e:"🏠"},
  {w:"big",ipa:"/bɪɡ/",vi:"to, lớn",vp:"bí-g",e:"🐘"},
  {w:"busy",ipa:"/ˈbɪzi/",vi:"đông đúc",vp:"bi-zi",e:"🚦",st:1},
  {w:"noisy",ipa:"/ˈnɔɪzi/",vi:"ồn ào",vp:"noi-zi",e:"🔊",st:1},
  {w:"quiet",ipa:"/ˈkwaɪət/",vi:"yên tĩnh",vp:"quai-ợt",e:"🤫",st:1}],
 pat:[["Where do you live?","I live on Le Loi Street."],["What's the street like?","It's busy."],["What's your road like?","It's quiet."]]},

{n:12,t:"Jobs",vi:"Nghề nghiệp",th:"family",e:"👮",
 comp:["Hỏi và trả lời về nghề nghiệp","Hỏi và trả lời về nơi làm việc"],
 focus:{label:"Phonics",items:["farmer","nurse"]},
 words:[
  {w:"actor",ipa:"/ˈæktə/",vi:"diễn viên (nam)",vp:"ec-tơ",e:"🎭",st:1},
  {w:"farmer",ipa:"/ˈfɑːmə/",vi:"nông dân",vp:"pha-mơ",e:"👨‍🌾",st:1},
  {w:"nurse",ipa:"/nɜːs/",vi:"y tá",vp:"nơ-x",e:"👩‍⚕️"},
  {w:"office worker",ipa:"/ˈɒfɪs wɜːkə/",vi:"nhân viên văn phòng",vp:"ó-phịt uơ-cơ",e:"🧑‍💼"},
  {w:"policeman",ipa:"/pəˈliːsmən/",vi:"cảnh sát",vp:"pơ-li-x-mừn",e:"👮",st:2},
  {w:"factory",ipa:"/ˈfæktri/",vi:"nhà máy",vp:"phéc-tri",e:"🏭",st:1},
  {w:"farm",ipa:"/fɑːm/",vi:"nông trại",vp:"pha-m",e:"🚜"},
  {w:"hospital",ipa:"/ˈhɒspɪtl/",vi:"bệnh viện",vp:"hót-x-pi-tồ",e:"🏥",st:1},
  {w:"nursing home",ipa:"/ˈnɜːsɪŋ həʊm/",vi:"viện điều dưỡng",vp:"nơ-xing hâu-m",e:"🏡"}],
 pat:[["What does he do?","He's a policeman."],["Where does she work?","She works in a hospital."],["What does she do?","She's a nurse."]]},

{n:13,t:"Appearance",vi:"Ngoại hình",th:"family",e:"🧍",
 comp:["Hỏi và trả lời về ngoại hình của ai đó"],
 focus:{label:"Phonics",items:["long","round"]},
 words:[
  {w:"tall",ipa:"/tɔːl/",vi:"cao",vp:"tô-l",e:"🧍"},
  {w:"short",ipa:"/ʃɔːt/",vi:"thấp",vp:"sót",e:"🧒"},
  {w:"slim",ipa:"/slɪm/",vi:"mảnh khảnh",vp:"xlim",e:"🙍"},
  {w:"big",ipa:"/bɪɡ/",vi:"to",vp:"bí-g",e:"🧔"},
  {w:"eyes",ipa:"/aɪz/",vi:"đôi mắt",vp:"ai-z",e:"👀"},
  {w:"face",ipa:"/feɪs/",vi:"khuôn mặt",vp:"phêi-s",e:"😀"},
  {w:"hair",ipa:"/heə/",vi:"tóc",vp:"he-ơ",e:"💇"},
  {w:"long",ipa:"/lɒŋ/",vi:"dài",vp:"lo-ng",e:"📏"},
  {w:"round",ipa:"/raʊnd/",vi:"tròn",vp:"rao-n-đ",e:"⭕"}],
 pat:[["What does he look like?","He's tall and slim."],["What does she look like?","She has long hair."],["What does he look like?","He has a round face."]]},

{n:14,t:"Daily activities",vi:"Hoạt động hằng ngày",th:"family",e:"🧺",
 comp:["Hỏi và trả lời về thời điểm làm một việc","Hỏi và trả lời về việc làm hằng ngày"],
 focus:{label:"Phonics",items:["watch","wash"]},
 words:[
  {w:"in the morning",ipa:"/ɪn ðə ˈmɔːnɪŋ/",vi:"vào buổi sáng",vp:"in đờ mo-ning",e:"🌅"},
  {w:"at noon",ipa:"/ət nuːn/",vi:"vào buổi trưa",vp:"ét nu-n",e:"🌞"},
  {w:"in the afternoon",ipa:"/ɪn ðə ˌɑːftəˈnuːn/",vi:"vào buổi chiều",vp:"in đờ áp-tơ-nu-n",e:"🌇"},
  {w:"in the evening",ipa:"/ɪn ðə ˈiːvnɪŋ/",vi:"vào buổi tối",vp:"in đờ i-v-ning",e:"🌆"},
  {w:"clean the floor",ipa:"/kliːn ðə flɔː/",vi:"lau nhà",vp:"cli-n đờ phlo",e:"🧹"},
  {w:"wash the dishes",ipa:"/wɒʃ ðə ˈdɪʃɪz/",vi:"rửa bát",vp:"oó-sơ đờ đí-sịz",e:"🍽️"},
  {w:"wash the clothes",ipa:"/wɒʃ ðə kləʊðz/",vi:"giặt quần áo",vp:"oó-sơ đờ clâu-đ-z",e:"🧺"},
  {w:"help with the cooking",ipa:"/help wɪð ðə ˈkʊkɪŋ/",vi:"phụ nấu ăn",vp:"heo-p uít đờ cúc-king",e:"🍳"}],
 pat:[["When do you watch TV?","I watch TV in the evening."],["What do you do in the morning?","I clean the floor."],["When do you wash the dishes?","I wash the dishes at noon."]]},

{n:15,t:"My family's weekends",vi:"Cuối tuần của gia đình em",th:"family",e:"🏊",
 comp:["Hỏi và trả lời về nơi ai đó đến vào cuối tuần","Hỏi và trả lời về việc ai đó làm"],
 focus:{label:"Phonics",items:["go","television"]},
 words:[
  {w:"cinema",ipa:"/ˈsɪnəmə/",vi:"rạp chiếu phim",vp:"xi-nơ-mơ",e:"🎬",st:1},
  {w:"shopping centre",ipa:"/ˈʃɒpɪŋ sentə/",vi:"trung tâm mua sắm",vp:"sóp-ping xen-tơ",e:"🏬"},
  {w:"sports centre",ipa:"/ˈspɔːts sentə/",vi:"trung tâm thể thao",vp:"xpo-t-s xen-tơ",e:"🏟️"},
  {w:"swimming pool",ipa:"/ˈswɪmɪŋ puːl/",vi:"bể bơi",vp:"xuim-ming pu-l",e:"🏊"},
  {w:"cook meals",ipa:"/kʊk miːlz/",vi:"nấu các bữa ăn",vp:"cúc mi-l-z",e:"🍲"},
  {w:"do yoga",ipa:"/duː ˈjəʊɡə/",vi:"tập yoga",vp:"đu dâu-gơ",e:"🧘"},
  {w:"play tennis",ipa:"/pleɪ ˈtenɪs/",vi:"chơi quần vợt",vp:"plêi ten-nít",e:"🎾"},
  {w:"watch films",ipa:"/wɒtʃ fɪlmz/",vi:"xem phim",vp:"oách phi-l-m-z",e:"🎞️"}],
 pat:[["Where does he go on Saturdays?","He goes to the swimming pool."],["What does she do on Sundays?","She does yoga."],["Where does she go on Saturdays?","She goes to the cinema."]]},

{n:16,t:"Weather",vi:"Thời tiết",th:"world",e:"🌤️",
 comp:["Hỏi và trả lời về thời tiết trong quá khứ","Rủ đi đâu đó và đáp lời"],
 focus:{label:"Trọng âm",items:["'sunny","'rainy"]},
 words:[
  {w:"sunny",ipa:"/ˈsʌni/",vi:"có nắng",vp:"xa-ni",e:"☀️",st:1},
  {w:"rainy",ipa:"/ˈreɪni/",vi:"có mưa",vp:"rêi-ni",e:"🌧️",st:1},
  {w:"cloudy",ipa:"/ˈklaʊdi/",vi:"nhiều mây",vp:"clao-đi",e:"☁️",st:1},
  {w:"windy",ipa:"/ˈwɪndi/",vi:"có gió",vp:"uin-đi",e:"💨",st:1},
  {w:"weather",ipa:"/ˈweðə/",vi:"thời tiết",vp:"ue-đơ",e:"🌤️",st:1},
  {w:"bakery",ipa:"/ˈbeɪkəri/",vi:"tiệm bánh",vp:"bêi-cơ-ri",e:"🥐",st:1},
  {w:"bookshop",ipa:"/ˈbʊkʃɒp/",vi:"hiệu sách",vp:"búc-sóp",e:"📚",st:1},
  {w:"food stall",ipa:"/ˈfuːd stɔːl/",vi:"quầy đồ ăn",vp:"phu-đ xtô-l",e:"🍢"},
  {w:"water park",ipa:"/ˈwɔːtə pɑːk/",vi:"công viên nước",vp:"uô-tơ pác",e:"🎢"}],
 pat:[["What was the weather like last weekend?","It was sunny."],["Do you want to go to the bookshop?","Great! Let's go."],["Do you want to go to the water park?","Sorry, I can't."]]},

{n:17,t:"In the city",vi:"Trong thành phố",th:"world",e:"🚦",
 comp:["Nhận biết biển báo giao thông","Hỏi và chỉ đường"],
 focus:{label:"Trọng âm",items:["'bookshop","'campsite"]},
 words:[
  {w:"go straight",ipa:"/ɡəʊ streɪt/",vi:"đi thẳng",vp:"gâu xtrêi-t",e:"⬆️"},
  {w:"turn left",ipa:"/tɜːn left/",vi:"rẽ trái",vp:"tơn lép-t",e:"⬅️"},
  {w:"turn right",ipa:"/tɜːn raɪt/",vi:"rẽ phải",vp:"tơn rai-t",e:"➡️"},
  {w:"turn round",ipa:"/tɜːn raʊnd/",vi:"quay lại",vp:"tơn rao-n-đ",e:"🔄"},
  {w:"stop",ipa:"/stɒp/",vi:"dừng lại",vp:"xtóp",e:"🛑"},
  {w:"left",ipa:"/left/",vi:"bên trái",vp:"lép-t",e:"👈"},
  {w:"right",ipa:"/raɪt/",vi:"bên phải",vp:"rai-t",e:"👉"}],
 pat:[["What does it say?","It says 'Stop'."],["How can I get to the bookshop?","Go straight and turn left."],["How can I get to the park?","Turn right."]]},

{n:18,t:"At the shopping centre",vi:"Ở trung tâm mua sắm",th:"world",e:"🛍️",
 comp:["Hỏi và trả lời về vị trí","Hỏi và trả lời về giá cả"],
 focus:{label:"Trọng âm",items:["be'hind","be'tween"]},
 words:[
  {w:"behind",ipa:"/bɪˈhaɪnd/",vi:"phía sau",vp:"bi-hai-n-đ",e:"🔙",st:2},
  {w:"between",ipa:"/bɪˈtwiːn/",vi:"ở giữa",vp:"bi-tuy-n",e:"↔️",st:2},
  {w:"near",ipa:"/nɪə/",vi:"gần",vp:"ni-ơ",e:"📍"},
  {w:"opposite",ipa:"/ˈɒpəzɪt/",vi:"đối diện",vp:"ó-pơ-zịt",e:"🔀",st:1},
  {w:"gift shop",ipa:"/ˈɡɪft ʃɒp/",vi:"cửa hàng quà tặng",vp:"ghíp-t sóp",e:"🎁"},
  {w:"skirt",ipa:"/skɜːt/",vi:"cái váy",vp:"xcơ-t",e:"👗"},
  {w:"T-shirt",ipa:"/ˈtiː ʃɜːt/",vi:"áo phông",vp:"ti-sơ-t",e:"👕",st:1},
  {w:"thousand",ipa:"/ˈθaʊznd/",vi:"nghìn",vp:"thao-zần-đ",e:"🔢",st:1},
  {w:"dong",ipa:"/dɒŋ/",vi:"đồng (tiền Việt)",vp:"đong",e:"💵"}],
 pat:[["Where's the bookshop?","It's behind the gift shop."],["How much is the skirt?","It's two hundred thousand dong."],["Where's the gift shop?","It's between the bakery and the bookshop."]]},

{n:19,t:"The animal world",vi:"Thế giới loài vật",th:"world",e:"🦁",
 comp:["Hỏi và trả lời về các con vật","Hỏi và nêu lí do yêu thích một con vật"],
 focus:{label:"Trọng âm",items:["'loudly","'quickly"]},
 words:[
  {w:"crocodiles",ipa:"/ˈkrɒkədaɪlz/",vi:"cá sấu",vp:"cró-cơ-đai-l-z",e:"🐊",st:1},
  {w:"giraffes",ipa:"/dʒəˈrɑːfs/",vi:"hươu cao cổ",vp:"giơ-ráp-s",e:"🦒",st:2},
  {w:"hippos",ipa:"/ˈhɪpəʊz/",vi:"hà mã",vp:"hi-pâu-z",e:"🦛",st:1},
  {w:"lions",ipa:"/ˈlaɪənz/",vi:"sư tử",vp:"lai-ừn-z",e:"🦁",st:1},
  {w:"roar loudly",ipa:"/rɔː ˈlaʊdli/",vi:"gầm to",vp:"ro lao-đ-li",e:"📢"},
  {w:"run quickly",ipa:"/rʌn ˈkwɪkli/",vi:"chạy nhanh",vp:"răn quích-li",e:"💨"},
  {w:"sing merrily",ipa:"/sɪŋ ˈmerəli/",vi:"hót vui vẻ",vp:"xing me-rơ-li",e:"🎶"},
  {w:"dance beautifully",ipa:"/dɑːns ˈbjuːtɪfli/",vi:"nhảy đẹp",vp:"đan-s biu-ti-phli",e:"💃"}],
 pat:[["What are these animals?","They're giraffes."],["Why do you like lions?","Because they roar loudly."],["Why do you like giraffes?","Because they run quickly."]]},

{n:20,t:"At summer camp",vi:"Ở trại hè",th:"world",e:"🏕️",
 comp:["Hỏi và trả lời về việc một người đang làm","Hỏi và trả lời về việc nhiều người đang làm"],
 focus:{label:"Trọng âm",items:["'visit","'email"]},
 words:[
  {w:"putting up a tent",ipa:"/ˈpʊtɪŋ ʌp ə tent/",vi:"dựng lều",vp:"pút-ting ắp ơ ten-t",e:"⛺"},
  {w:"building a campfire",ipa:"/ˈbɪldɪŋ ə ˈkæmpfaɪə/",vi:"nhóm lửa trại",vp:"biu-đing ơ kem-p-phai-ơ",e:"🔥"},
  {w:"dancing around the campfire",ipa:"/ˈdɑːnsɪŋ əˈraʊnd ðə ˈkæmpfaɪə/",vi:"nhảy quanh lửa trại",vp:"đan-xing ơ-rao-n-đ đờ kem-p-phai-ơ",e:"💃"},
  {w:"playing card games",ipa:"/ˈpleɪɪŋ kɑːd ɡeɪmz/",vi:"chơi bài",vp:"plêi-ing cá-đ ghêi-m-z",e:"🃏"},
  {w:"playing tug of war",ipa:"/ˈpleɪɪŋ tʌɡ əv wɔː/",vi:"kéo co",vp:"plêi-ing tắc ợv uo",e:"🪢"},
  {w:"singing songs",ipa:"/ˈsɪŋɪŋ sɒŋz/",vi:"hát các bài hát",vp:"xing-ing xong-z",e:"🎤"},
  {w:"taking a photo",ipa:"/ˈteɪkɪŋ ə ˈfəʊtəʊ/",vi:"chụp ảnh",vp:"têi-king ơ phâu-tâu",e:"📸"},
  {w:"telling a story",ipa:"/ˈtelɪŋ ə ˈstɔːri/",vi:"kể chuyện",vp:"te-ling ơ xto-ri",e:"📖"},
  {w:"visit",ipa:"/ˈvɪzɪt/",vi:"thăm",vp:"vi-zịt",e:"🚶",st:1},
  {w:"email",ipa:"/ˈiːmeɪl/",vi:"thư điện tử",vp:"i-mêi-l",e:"📧",st:1}],
 pat:[["What's he doing?","He's putting up a tent."],["What are they doing?","They're singing songs."],["What's she doing?","She's taking a photo."]]}
];

const G4_GROUPS = [
 {label:"ME AND MY FRIENDS",vi:"Em và bạn bè",icon:"🧑‍🤝‍🧑",units:[1,2,3,4,5]},
 {label:"ME AND MY SCHOOL",vi:"Em và trường học",icon:"🏫",units:[6,7,8,9,10]},
 {label:"ME AND MY FAMILY",vi:"Em và gia đình",icon:"👨‍👩‍👧",units:[11,12,13,14,15]},
 {label:"ME AND THE WORLD AROUND",vi:"Em và thế giới quanh em",icon:"🌏",units:[16,17,18,19,20]}
];

Object.assign(TRANS, {
"Where are you from?":"Bạn đến từ đâu?",
"I'm from Viet Nam.":"Mình đến từ Việt Nam.",
"Where's he from?":"Bạn ấy đến từ đâu?",
"He's from Japan.":"Bạn ấy đến từ Nhật Bản.",
"Where's she from?":"Bạn ấy đến từ đâu?",
"She's from Australia.":"Bạn ấy đến từ nước Úc.",
"What time is it?":"Bây giờ là mấy giờ?",
"It's six o'clock.":"Bây giờ là sáu giờ.",
"What time do you get up?":"Bạn thức dậy lúc mấy giờ?",
"I get up at six.":"Mình thức dậy lúc sáu giờ.",
"What time do you go to bed?":"Bạn đi ngủ lúc mấy giờ?",
"I go to bed at nine thirty.":"Mình đi ngủ lúc chín giờ ba mươi.",
"What day is it today?":"Hôm nay là thứ mấy?",
"It's Monday.":"Hôm nay là thứ Hai.",
"What do you do on Sundays?":"Chủ nhật bạn làm gì?",
"I listen to music.":"Mình nghe nhạc.",
"What do you do on Saturdays?":"Thứ Bảy bạn làm gì?",
"I do housework.":"Mình làm việc nhà.",
"When's your birthday?":"Sinh nhật bạn khi nào?",
"It's in April.":"Vào tháng Tư.",
"What do you want to eat?":"Bạn muốn ăn gì?",
"I want some chips.":"Mình muốn ăn ít khoai tây chiên.",
"What do you want to drink?":"Bạn muốn uống gì?",
"I want some lemonade.":"Mình muốn uống nước chanh.",
"Can you swim?":"Bạn biết bơi không?",
"Yes, I can.":"Có, mình biết.",
"Can he ride a horse?":"Bạn ấy biết cưỡi ngựa không?",
"No, he can't, but he can ride a bike.":"Không, nhưng bạn ấy biết đi xe đạp.",
"Can she play the piano?":"Bạn ấy biết chơi piano không?",
"Yes, she can.":"Có, bạn ấy biết.",
"Where's your school?":"Trường bạn ở đâu?",
"It's in the city.":"Trường mình ở trong thành phố.",
"How many buildings are there at your school?":"Trường bạn có mấy toà nhà?",
"There are three.":"Có ba toà.",
"How many computer rooms are there?":"Có mấy phòng máy tính?",
"There is one.":"Có một phòng.",
"What subjects do you have today?":"Hôm nay bạn học những môn gì?",
"I have maths and English.":"Mình học Toán và Tiếng Anh.",
"When do you have music?":"Bạn học Âm nhạc vào hôm nào?",
"I have it on Monday.":"Mình học vào thứ Hai.",
"When do you have science?":"Bạn học Khoa học vào hôm nào?",
"I have it on Friday.":"Mình học vào thứ Sáu.",
"What's your favourite subject?":"Môn học bạn thích nhất là gì?",
"It's maths.":"Đó là môn Toán.",
"Why do you like maths?":"Vì sao bạn thích Toán?",
"Because I want to be a maths teacher.":"Vì mình muốn làm giáo viên Toán.",
"Why do you like art?":"Vì sao bạn thích Mĩ thuật?",
"Because I want to be a painter.":"Vì mình muốn làm hoạ sĩ.",
"Is your sports day in May?":"Ngày hội thể thao của trường bạn vào tháng Năm à?",
"Yes, it is.":"Đúng vậy.",
"When's your sports day?":"Ngày hội thể thao của trường bạn khi nào?",
"It's in December.":"Vào tháng Mười hai.",
"Is your sports day in July?":"Ngày hội thể thao vào tháng Bảy à?",
"No, it isn't. It's in October.":"Không. Vào tháng Mười.",
"Were you at the beach last weekend?":"Cuối tuần trước bạn có ở bãi biển không?",
"Yes, I was.":"Có, mình có ở đó.",
"Where were you last summer?":"Mùa hè năm ngoái bạn ở đâu?",
"I was in London.":"Mình ở Luân Đôn.",
"Were you in Tokyo last summer?":"Mùa hè năm ngoái bạn ở Tô-ki-ô à?",
"No, I wasn't.":"Không, mình không ở đó.",
"Where do you live?":"Bạn sống ở đâu?",
"I live on Le Loi Street.":"Mình sống ở phố Lê Lợi.",
"What's the street like?":"Con phố đó thế nào?",
"It's busy.":"Nó đông đúc.",
"What's your road like?":"Con đường nhà bạn thế nào?",
"It's quiet.":"Nó yên tĩnh.",
"What does he do?":"Chú ấy làm nghề gì?",
"He's a policeman.":"Chú ấy là cảnh sát.",
"Where does she work?":"Cô ấy làm việc ở đâu?",
"She works in a hospital.":"Cô ấy làm ở bệnh viện.",
"What does she do?":"Cô ấy làm nghề gì?",
"She's a nurse.":"Cô ấy là y tá.",
"What does he look like?":"Bạn ấy trông thế nào?",
"He's tall and slim.":"Bạn ấy cao và mảnh khảnh.",
"What does she look like?":"Bạn ấy trông thế nào?",
"She has long hair.":"Bạn ấy có mái tóc dài.",
"He has a round face.":"Bạn ấy có khuôn mặt tròn.",
"When do you watch TV?":"Bạn xem TV lúc nào?",
"I watch TV in the evening.":"Mình xem TV vào buổi tối.",
"What do you do in the morning?":"Buổi sáng bạn làm gì?",
"I clean the floor.":"Mình lau nhà.",
"When do you wash the dishes?":"Bạn rửa bát lúc nào?",
"I wash the dishes at noon.":"Mình rửa bát vào buổi trưa.",
"Where does he go on Saturdays?":"Thứ Bảy chú ấy đi đâu?",
"He goes to the swimming pool.":"Chú ấy đến bể bơi.",
"What does she do on Sundays?":"Chủ nhật cô ấy làm gì?",
"She does yoga.":"Cô ấy tập yoga.",
"Where does she go on Saturdays?":"Thứ Bảy cô ấy đi đâu?",
"She goes to the cinema.":"Cô ấy đến rạp chiếu phim.",
"What was the weather like last weekend?":"Cuối tuần trước thời tiết thế nào?",
"It was sunny.":"Trời có nắng.",
"Do you want to go to the bookshop?":"Bạn có muốn đến hiệu sách không?",
"Great! Let's go.":"Tuyệt! Đi thôi.",
"Do you want to go to the water park?":"Bạn có muốn đến công viên nước không?",
"Sorry, I can't.":"Xin lỗi, mình không đi được.",
"What does it say?":"Biển báo ghi gì?",
"It says 'Stop'.":"Nó ghi “Dừng lại”.",
"How can I get to the bookshop?":"Làm sao để đến hiệu sách?",
"Go straight and turn left.":"Đi thẳng rồi rẽ trái.",
"How can I get to the park?":"Làm sao để đến công viên?",
"Turn right.":"Rẽ phải.",
"Where's the bookshop?":"Hiệu sách ở đâu?",
"It's behind the gift shop.":"Nó ở phía sau cửa hàng quà tặng.",
"How much is the skirt?":"Cái váy giá bao nhiêu?",
"It's two hundred thousand dong.":"Giá hai trăm nghìn đồng.",
"Where's the gift shop?":"Cửa hàng quà tặng ở đâu?",
"It's between the bakery and the bookshop.":"Nó ở giữa tiệm bánh và hiệu sách.",
"What are these animals?":"Đây là những con gì?",
"They're giraffes.":"Chúng là hươu cao cổ.",
"Why do you like lions?":"Vì sao bạn thích sư tử?",
"Because they roar loudly.":"Vì chúng gầm rất to.",
"Why do you like giraffes?":"Vì sao bạn thích hươu cao cổ?",
"Because they run quickly.":"Vì chúng chạy rất nhanh.",
"What's he doing?":"Bạn ấy đang làm gì?",
"He's putting up a tent.":"Bạn ấy đang dựng lều.",
"What are they doing?":"Các bạn ấy đang làm gì?",
"They're singing songs.":"Các bạn ấy đang hát.",
"What's she doing?":"Bạn ấy đang làm gì?",
"She's taking a photo.":"Bạn ấy đang chụp ảnh."
});

/* =====================================================================
   LỚP 5 – Tiếng Anh 5 Global Success (GDPT 2018) · 20 Unit · 4 chủ điểm
   Cột phát âm của SGK đổi theo tập: Trọng âm (U1–10) · Nhịp câu (U11–15)
   · Ngữ điệu (U16–20)
   ===================================================================== */
const G5 = [
{n:1,t:"All about me!",vi:"Tất cả về em",th:"friends",e:"🙋",
 comp:["Hỏi và trả lời về thông tin cá nhân","Hỏi và trả lời về những thứ mình yêu thích"],
 focus:{label:"Trọng âm",items:["'dolphin","'tennis"]},
 words:[
  {w:"city",ipa:"/ˈsɪti/",vi:"thành phố",vp:"xi-ti",e:"🏙️",st:1},
  {w:"countryside",ipa:"/ˈkʌntrisaɪd/",vi:"vùng quê",vp:"căn-tri-xai-đ",e:"🌄",st:1},
  {w:"class",ipa:"/klɑːs/",vi:"lớp học",vp:"cla-s",e:"🧑‍🏫"},
  {w:"dolphin",ipa:"/ˈdɒlfɪn/",vi:"cá heo",vp:"đôn-phin",e:"🐬",st:1},
  {w:"pink",ipa:"/pɪŋk/",vi:"màu hồng",vp:"ping-k",e:"💗"},
  {w:"sandwich",ipa:"/ˈsænwɪtʃ/",vi:"bánh mì kẹp",vp:"xen-uịch",e:"🥪",st:1},
  {w:"table tennis",ipa:"/ˈteɪbl tenɪs/",vi:"bóng bàn",vp:"tê-bồ ten-nít",e:"🏓"}],
 pat:[["Can you tell me about yourself?","I'm Mai. I'm ten years old."],["What's your favourite animal?","It's a dolphin."],["What's your favourite sport?","It's table tennis."]]},

{n:2,t:"Our homes",vi:"Nhà của chúng em",th:"friends",e:"🏢",
 comp:["Hỏi và trả lời về nơi ai đó sống","Hỏi và trả lời về địa chỉ"],
 focus:{label:"Trọng âm",items:["fif'teen","six'teen"]},
 words:[
  {w:"building",ipa:"/ˈbɪldɪŋ/",vi:"toà nhà",vp:"biu-đing",e:"🏢",st:1},
  {w:"flat",ipa:"/flæt/",vi:"căn hộ",vp:"phlét",e:"🏠"},
  {w:"house",ipa:"/haʊs/",vi:"ngôi nhà",vp:"hao-s",e:"🏡"},
  {w:"tower",ipa:"/ˈtaʊə/",vi:"toà tháp",vp:"tao-ơ",e:"🗼",st:1},
  {w:"address",ipa:"/əˈdres/",vi:"địa chỉ",vp:"ơ-đrét",e:"📮",st:2},
  {w:"fifteen",ipa:"/ˌfɪfˈtiːn/",vi:"số mười lăm (15)",vp:"phíp-ti-n",e:"1️⃣5️⃣",st:2},
  {w:"sixteen",ipa:"/ˌsɪkˈstiːn/",vi:"số mười sáu (16)",vp:"xích-x-ti-n",e:"1️⃣6️⃣",st:2},
  {w:"twenty-three",ipa:"/ˌtwentiˈθriː/",vi:"số hai mươi ba (23)",vp:"tuen-ti-thri",e:"2️⃣3️⃣",st:3},
  {w:"thirty-eight",ipa:"/ˌθɜːtiˈeɪt/",vi:"số ba mươi tám (38)",vp:"thơ-ti-êi-t",e:"3️⃣8️⃣",st:3},
  {w:"ninety-three",ipa:"/ˌnaɪntiˈθriː/",vi:"số chín mươi ba (93)",vp:"nai-n-ti-thri",e:"9️⃣3️⃣",st:3},
  {w:"one hundred and sixteen",ipa:"/wʌn ˈhʌndrəd ənd ˌsɪkˈstiːn/",vi:"số một trăm mười sáu (116)",vp:"oăn hăn-đrịt ừn xích-x-ti-n",e:"💯"}],
 pat:[["Do you live in this tower?","Yes, I do."],["Do you live in that flat?","No, I don't."],["What's your address?","It's 116 Nguyen Trai Street."]]},

{n:3,t:"My foreign friends",vi:"Bạn nước ngoài của em",th:"friends",e:"🌍",
 comp:["Hỏi và trả lời về quốc tịch","Hỏi và trả lời về tính cách của ai đó"],
 focus:{label:"Trọng âm",items:["'active","'friendly"]},
 words:[
  {w:"American",ipa:"/əˈmerɪkən/",vi:"người Mỹ",vp:"ơ-me-ri-cừn",e:"🇺🇸",st:2},
  {w:"Australian",ipa:"/ɒˈstreɪliən/",vi:"người Úc",vp:"ót-xtrêi-li-ừn",e:"🇦🇺",st:2},
  {w:"Japanese",ipa:"/ˌdʒæpəˈniːz/",vi:"người Nhật",vp:"gie-pơ-ni-z",e:"🇯🇵",st:3},
  {w:"Malaysian",ipa:"/məˈleɪziən/",vi:"người Ma-lai-xi-a",vp:"mơ-lêi-zi-ừn",e:"🇲🇾",st:2},
  {w:"active",ipa:"/ˈæktɪv/",vi:"năng động",vp:"ec-tịv",e:"🏃",st:1},
  {w:"clever",ipa:"/ˈklevə/",vi:"thông minh",vp:"cle-vơ",e:"🧠",st:1},
  {w:"friendly",ipa:"/ˈfrendli/",vi:"thân thiện",vp:"phren-đ-li",e:"😊",st:1},
  {w:"helpful",ipa:"/ˈhelpfl/",vi:"hay giúp đỡ",vp:"heo-p-phồ",e:"🤝",st:1}],
 pat:[["What nationality is he?","He's Japanese."],["What's she like?","She's friendly and helpful."],["What nationality is she?","She's Australian."]]},

{n:4,t:"Our free-time activities",vi:"Hoạt động lúc rảnh rỗi",th:"friends",e:"🎻",
 comp:["Hỏi và trả lời về việc thích làm lúc rảnh","Hỏi và trả lời về việc làm cuối tuần"],
 focus:{label:"Trọng âm",items:["'always","'sometimes"]},
 words:[
  {w:"go for a walk",ipa:"/ɡəʊ fər ə wɔːk/",vi:"đi dạo",vp:"gâu pho ơ uóc",e:"🚶"},
  {w:"play the violin",ipa:"/pleɪ ðə ˌvaɪəˈlɪn/",vi:"chơi vĩ cầm",vp:"plêi đờ vai-ơ-lin",e:"🎻"},
  {w:"surf the Internet",ipa:"/sɜːf ði ˈɪntənet/",vi:"lướt mạng",vp:"xơ-phơ đi in-tơ-nét",e:"💻"},
  {w:"water the flowers",ipa:"/ˈwɔːtə ðə ˈflaʊəz/",vi:"tưới hoa",vp:"uô-tơ đờ phlao-ơ-z",e:"🌻"},
  {w:"always",ipa:"/ˈɔːlweɪz/",vi:"luôn luôn",vp:"ôn-uêi-z",e:"💯",st:1},
  {w:"often",ipa:"/ˈɒfn/",vi:"thường xuyên",vp:"ó-phừn",e:"🔁",st:1},
  {w:"sometimes",ipa:"/ˈsʌmtaɪmz/",vi:"thỉnh thoảng",vp:"xăm-tai-m-z",e:"🔀",st:1},
  {w:"usually",ipa:"/ˈjuːʒuəli/",vi:"thường thường",vp:"diu-giu-ơ-li",e:"⏳",st:1}],
 pat:[["What do you like doing in your free time?","I like playing the violin."],["What do you do at the weekend?","I usually water the flowers."],["What do you like doing in your free time?","I like surfing the Internet."]]},

{n:5,t:"My future job",vi:"Nghề tương lai của em",th:"friends",e:"🧑‍🚒",
 comp:["Hỏi và trả lời về nghề muốn làm trong tương lai","Hỏi và nêu lí do"],
 focus:{label:"Trọng âm",items:["'teacher","'dentist"]},
 words:[
  {w:"firefighter",ipa:"/ˈfaɪəfaɪtə/",vi:"lính cứu hoả",vp:"phai-ơ-phai-tơ",e:"🧑‍🚒",st:1},
  {w:"gardener",ipa:"/ˈɡɑːdnə/",vi:"người làm vườn",vp:"ga-đơ-nơ",e:"👨‍🌾",st:1},
  {w:"reporter",ipa:"/rɪˈpɔːtə/",vi:"phóng viên",vp:"ri-po-tơ",e:"🎙️",st:2},
  {w:"writer",ipa:"/ˈraɪtə/",vi:"nhà văn",vp:"rai-tơ",e:"✍️",st:1},
  {w:"dentist",ipa:"/ˈdentɪst/",vi:"nha sĩ",vp:"đen-tịt",e:"🦷",st:1},
  {w:"grow flowers",ipa:"/ɡrəʊ ˈflaʊəz/",vi:"trồng hoa",vp:"grâu phlao-ơ-z",e:"🌷"},
  {w:"report the news",ipa:"/rɪˈpɔːt ðə njuːz/",vi:"đưa tin",vp:"ri-po-t đờ niu-z",e:"📰"},
  {w:"teach children",ipa:"/tiːtʃ ˈtʃɪldrən/",vi:"dạy trẻ em",vp:"tích chiu-đrừn",e:"🧑‍🏫"},
  {w:"write stories",ipa:"/raɪt ˈstɔːriz/",vi:"viết truyện",vp:"rai-t xto-ri-z",e:"📖"}],
 pat:[["What would you like to be in the future?","I'd like to be a writer."],["Why would you like to be a writer?","Because I'd like to write stories."],["What would you like to be in the future?","I'd like to be a firefighter."]]},

{n:6,t:"Our school rooms",vi:"Các phòng ở trường em",th:"school",e:"🏫",
 comp:["Hỏi và trả lời về vị trí phòng học","Hỏi và chỉ đường trong trường"],
 focus:{label:"Trọng âm",items:["up'stairs","down'stairs"]},
 words:[
  {w:"ground floor",ipa:"/ɡraʊnd flɔː/",vi:"tầng trệt",vp:"grao-n-đ phlo",e:"🏢"},
  {w:"first floor",ipa:"/fɜːst flɔː/",vi:"tầng một",vp:"phơ-x-t phlo",e:"1️⃣"},
  {w:"second floor",ipa:"/ˈsekənd flɔː/",vi:"tầng hai",vp:"xe-cừn-đ phlo",e:"2️⃣"},
  {w:"third floor",ipa:"/θɜːd flɔː/",vi:"tầng ba",vp:"thơ-đ phlo",e:"3️⃣"},
  {w:"upstairs",ipa:"/ˌʌpˈsteəz/",vi:"lên gác",vp:"ắp-xte-ơ-z",e:"⬆️",st:2},
  {w:"downstairs",ipa:"/ˌdaʊnˈsteəz/",vi:"xuống gác",vp:"đao-n-xte-ơ-z",e:"⬇️",st:2},
  {w:"go along",ipa:"/ɡəʊ əˈlɒŋ/",vi:"đi dọc theo",vp:"gâu ơ-long",e:"➡️"},
  {w:"go past",ipa:"/ɡəʊ pɑːst/",vi:"đi qua",vp:"gâu pá-x-t",e:"🚶"}],
 pat:[["Where's the art room?","It's on the second floor."],["Could you tell me the way to the computer room, please?","Go upstairs and go past the library."],["Where's the library?","It's on the ground floor."]]},

{n:7,t:"Our favourite school activities",vi:"Hoạt động ở trường em thích",th:"school",e:"📚",
 comp:["Hỏi và trả lời về hoạt động yêu thích ở trường","Hỏi và nêu lí do thích"],
 focus:{label:"Trọng âm",items:["'solving","'reading"]},
 words:[
  {w:"do projects",ipa:"/duː ˈprɒdʒekts/",vi:"làm dự án",vp:"đu pró-giếch-t-s",e:"📊"},
  {w:"play games",ipa:"/pleɪ ɡeɪmz/",vi:"chơi trò chơi",vp:"plêi ghêi-m-z",e:"🎲"},
  {w:"read books",ipa:"/riːd bʊks/",vi:"đọc sách",vp:"ri-đ búc-s",e:"📖"},
  {w:"solve maths problems",ipa:"/sɒlv mæθs ˈprɒbləmz/",vi:"giải toán",vp:"xol-v mét-th pró-blơm-z",e:"➗"},
  {w:"fun",ipa:"/fʌn/",vi:"vui",vp:"phăn",e:"😄"},
  {w:"interesting",ipa:"/ˈɪntrəstɪŋ/",vi:"thú vị",vp:"in-trơ-x-ting",e:"✨",st:1},
  {w:"useful",ipa:"/ˈjuːsfl/",vi:"hữu ích",vp:"diu-x-phồ",e:"🛠️",st:1},
  {w:"good for group work",ipa:"/ɡʊd fə ɡruːp wɜːk/",vi:"tốt cho làm việc nhóm",vp:"gút pho grúp uơ-c",e:"👥"}],
 pat:[["What school activity does he like?","He likes reading books."],["Why does he like reading books?","Because he thinks it's interesting."],["What school activity does she like?","She likes doing projects."]]},

{n:8,t:"In our classroom",vi:"Trong lớp học của chúng em",th:"school",e:"✏️",
 comp:["Hỏi và trả lời về vị trí đồ dùng","Hỏi và trả lời về sở hữu"],
 focus:{label:"Trọng âm",items:["a'bove","be'side"]},
 words:[
  {w:"above",ipa:"/əˈbʌv/",vi:"phía trên",vp:"ơ-ba-v",e:"⬆️",st:2},
  {w:"beside",ipa:"/bɪˈsaɪd/",vi:"bên cạnh",vp:"bi-xai-đ",e:"↔️",st:2},
  {w:"in front of",ipa:"/ɪn frʌnt əv/",vi:"phía trước",vp:"in phrăn-t ợv",e:"⏩"},
  {w:"under",ipa:"/ˈʌndə/",vi:"phía dưới",vp:"ăn-đơ",e:"⬇️",st:1},
  {w:"crayon",ipa:"/ˈkreɪən/",vi:"bút sáp màu",vp:"crêi-ừn",e:"🖍️",st:1},
  {w:"glue stick",ipa:"/ˈɡluː stɪk/",vi:"hồ dán",vp:"glu xtích",e:"🧴"},
  {w:"pencil sharpener",ipa:"/ˈpensl ʃɑːpnə/",vi:"gọt bút chì",vp:"pen-xồ sá-p-nơ",e:"✏️"},
  {w:"set square",ipa:"/set skweə/",vi:"cái ê ke",vp:"xét xquê-ơ",e:"📐"}],
 pat:[["Where are the crayons?","They're above the desk."],["Whose glue stick is this?","It's Mai's."],["Where's the set square?","It's under the book."]]},

{n:9,t:"Our outdoor activities",vi:"Hoạt động ngoài trời",th:"school",e:"🎡",
 comp:["Hỏi và trả lời về nơi đã đến","Hỏi và trả lời về việc đã làm"],
 focus:{label:"Trọng âm",items:["'cinema","'bakery"]},
 words:[
  {w:"aquarium",ipa:"/əˈkweəriəm/",vi:"thuỷ cung",vp:"ơ-quê-ri-ừm",e:"🐠",st:2},
  {w:"campsite",ipa:"/ˈkæmpsaɪt/",vi:"khu cắm trại",vp:"kem-p-xai-t",e:"⛺",st:1},
  {w:"funfair",ipa:"/ˈfʌnfeə/",vi:"khu vui chơi",vp:"phăn-phe-ơ",e:"🎡",st:1},
  {w:"theatre",ipa:"/ˈθɪətə/",vi:"nhà hát",vp:"thi-ơ-tơ",e:"🎭",st:1},
  {w:"cinema",ipa:"/ˈsɪnəmə/",vi:"rạp chiếu phim",vp:"xi-nơ-mơ",e:"🎬",st:1},
  {w:"bakery",ipa:"/ˈbeɪkəri/",vi:"tiệm bánh",vp:"bêi-cơ-ri",e:"🥐",st:1},
  {w:"play chess",ipa:"/pleɪ tʃes/",vi:"chơi cờ",vp:"plêi ché-x",e:"♟️"},
  {w:"watch the fish",ipa:"/wɒtʃ ðə fɪʃ/",vi:"ngắm cá",vp:"oách đờ phí-sơ",e:"🐟"},
  {w:"dance around the campfire",ipa:"/dɑːns əˈraʊnd ðə ˈkæmpfaɪə/",vi:"nhảy múa quanh lửa trại",vp:"đan-x ơ-rao-n-đ đờ kem-p-phai-ơ",e:"🔥"},
  {w:"listen to music",ipa:"/ˈlɪsn tə ˈmjuːzɪk/",vi:"nghe nhạc",vp:"li-xừn tu miu-zịch",e:"🎧"}],
 pat:[["Were you at the funfair yesterday?","Yes, we were."],["What did you do yesterday?","We watched the fish at the aquarium."],["Were you at the theatre yesterday?","No, we weren't."]]},

{n:10,t:"Our school trip",vi:"Chuyến đi của trường em",th:"school",e:"🚌",
 comp:["Hỏi và trả lời về chuyến đi đã qua","Hỏi và trả lời về việc đã làm ở đó"],
 focus:{label:"Trọng âm",items:["No'vember","De'cember"]},
 words:[
  {w:"Ba Na Hills",ipa:"/bɑː nɑː hɪlz/",vi:"Bà Nà Hills",vp:"ba na hiu-z",e:"🏔️"},
  {w:"Bai Dinh Pagoda",ipa:"/baɪ dɪn pəˈɡəʊdə/",vi:"chùa Bái Đính",vp:"bai đin pơ-gâu-đơ",e:"🛕"},
  {w:"Hoan Kiem Lake",ipa:"/hwɑːn kiəm leɪk/",vi:"hồ Hoàn Kiếm",vp:"hoan kiêm lêi-k",e:"🏞️"},
  {w:"Suoi Tien Theme Park",ipa:"/swɔɪ tiən θiːm pɑːk/",vi:"công viên Suối Tiên",vp:"xuôi tiên thim pác",e:"🎢"},
  {w:"plant trees",ipa:"/plɑːnt triːz/",vi:"trồng cây",vp:"plan-t tri-z",e:"🌳"},
  {w:"visit the old buildings",ipa:"/ˈvɪzɪt ðə əʊld ˈbɪldɪŋz/",vi:"tham quan nhà cổ",vp:"vi-zịt đờ âu-lđ biu-đing-z",e:"🏛️"},
  {w:"walk around the lake",ipa:"/wɔːk əˈraʊnd ðə leɪk/",vi:"đi bộ quanh hồ",vp:"uóc ơ-rao-n-đ đờ lêi-k",e:"🚶"},
  {w:"November",ipa:"/nəʊˈvembə/",vi:"tháng Mười một",vp:"nâu-vem-bơ",e:"🌧️",st:2},
  {w:"December",ipa:"/dɪˈsembə/",vi:"tháng Mười hai",vp:"đi-xem-bơ",e:"🎄",st:2}],
 pat:[["Did they go to Ba Na Hills?","Yes, they did."],["What did they do there?","They planted trees."],["Did they go to Hoan Kiem Lake?","No, they didn't."]]},

{n:11,t:"Family time",vi:"Thời gian bên gia đình",th:"family",e:"👨‍👩‍👧",
 comp:["Hỏi và trả lời về việc đã làm trong quá khứ","Hỏi và trả lời về việc gia đình đã làm"],
 focus:{label:"Nhịp câu",items:["When did you go to London?","What did they do in Finland?"]},
 words:[
  {w:"buy souvenirs",ipa:"/baɪ ˌsuːvəˈnɪəz/",vi:"mua đồ lưu niệm",vp:"bai xu-vơ-ni-ơ-z",e:"🛍️"},
  {w:"collect seashells",ipa:"/kəˈlekt ˈsiːʃelz/",vi:"nhặt vỏ sò",vp:"cơ-léc-t xi-seo-z",e:"🐚"},
  {w:"eat seafood",ipa:"/iːt ˈsiːfuːd/",vi:"ăn hải sản",vp:"i-t xi-phu-đ",e:"🦐"},
  {w:"see some interesting places",ipa:"/siː sʌm ˈɪntrəstɪŋ ˈpleɪsɪz/",vi:"tham quan vài nơi thú vị",vp:"xi xăm in-trơ-x-ting plêi-xịz",e:"🏞️"},
  {w:"take a boat trip around the bay",ipa:"/teɪk ə bəʊt trɪp əˈraʊnd ðə beɪ/",vi:"đi thuyền quanh vịnh",vp:"têi-k ơ bâu-t tríp ơ-rao-n-đ đờ bêi",e:"⛵"},
  {w:"walk on the beach",ipa:"/wɔːk ɒn ðə biːtʃ/",vi:"đi dạo trên bãi biển",vp:"uóc on đờ bích",e:"🏖️"},
  {w:"souvenir",ipa:"/ˌsuːvəˈnɪə/",vi:"đồ lưu niệm",vp:"xu-vơ-ni-ơ",e:"🎁",st:3},
  {w:"seashell",ipa:"/ˈsiːʃel/",vi:"vỏ sò",vp:"xi-seo",e:"🦪",st:1}],
 pat:[["Did you go to Ha Long Bay?","Yes, I did. I took a boat trip around the bay."],["What did your family do in Da Nang?","We walked on the beach."],["Did you eat seafood?","Yes, I did."]]},

{n:12,t:"Our Tet holiday",vi:"Tết của chúng em",th:"family",e:"🧧",
 comp:["Hỏi và trả lời về việc sẽ làm dịp Tết","Hỏi và trả lời về nơi sẽ đi"],
 focus:{label:"Nhịp câu",items:["I'll do the shopping for Tet.","We'll decorate our house with flowers."]},
 words:[
  {w:"buy roses",ipa:"/baɪ ˈrəʊzɪz/",vi:"mua hoa hồng",vp:"bai râu-zịz",e:"🌹"},
  {w:"buy a branch of peach blossoms",ipa:"/baɪ ə brɑːntʃ əv piːtʃ ˈblɒsəmz/",vi:"mua cành đào",vp:"bai ơ bran-ch ợv pích bló-xừm-z",e:"🌸"},
  {w:"decorate the house",ipa:"/ˈdekəreɪt ðə haʊs/",vi:"trang trí nhà",vp:"đe-cơ-rêi-t đờ hao-s",e:"🏠"},
  {w:"do the shopping",ipa:"/duː ðə ˈʃɒpɪŋ/",vi:"đi mua sắm",vp:"đu đờ sóp-ping",e:"🛒"},
  {w:"make banh chung",ipa:"/meɪk bɑːn tʃʊŋ/",vi:"gói bánh chưng",vp:"mêi-k bánh chưng",e:"🍚"},
  {w:"make spring rolls",ipa:"/meɪk sprɪŋ rəʊlz/",vi:"làm nem",vp:"mêi-k xpring râu-l-z",e:"🥟"},
  {w:"fireworks show",ipa:"/ˈfaɪəwɜːks ʃəʊ/",vi:"màn pháo hoa",vp:"phai-ơ-uơ-c-s sâu",e:"🎆"},
  {w:"flower festival",ipa:"/ˈflaʊə ˈfestɪvl/",vi:"lễ hội hoa",vp:"phlao-ơ phe-xti-vồ",e:"💐"},
  {w:"New Year party",ipa:"/njuː jɪə ˈpɑːti/",vi:"tiệc năm mới",vp:"niu di-ơ pa-ti",e:"🎉"},
  {w:"decorate",ipa:"/ˈdekəreɪt/",vi:"trang trí",vp:"đe-cơ-rêi-t",e:"🎏",st:1}],
 pat:[["Will you make banh chung for Tet?","Yes, I will."],["Where will you go at Tet?","I'll go to my grandparents' house."],["Will you buy roses for Tet?","No, I won't. I'll buy peach blossoms."]]},

{n:13,t:"Our special days",vi:"Những ngày đặc biệt",th:"family",e:"🎊",
 comp:["Hỏi và trả lời về việc sẽ làm trong ngày đặc biệt","Hỏi và trả lời về đồ ăn thức uống"],
 focus:{label:"Nhịp câu",items:["What food will you have at the party?","What drinks will you have at the party?"]},
 words:[
  {w:"at Mid-Autumn Festival",ipa:"/ət mɪd ˈɔːtəm ˈfestɪvl/",vi:"vào Tết Trung thu",vp:"ét mít ô-từm phe-xti-vồ",e:"🥮"},
  {w:"on Children's Day",ipa:"/ɒn ˈtʃɪldrənz deɪ/",vi:"vào ngày Quốc tế Thiếu nhi",vp:"on chiu-đrừn-z đêi",e:"🧒"},
  {w:"on Sports Day",ipa:"/ɒn spɔːts deɪ/",vi:"vào ngày hội thể thao",vp:"on xpo-t-s đêi",e:"🏃"},
  {w:"on Teachers' Day",ipa:"/ɒn ˈtiːtʃəz deɪ/",vi:"vào ngày Nhà giáo",vp:"on ti-chơ-z đêi",e:"👩‍🏫"},
  {w:"apple juice",ipa:"/ˈæpl dʒuːs/",vi:"nước táo",vp:"áp-pồ giu-s",e:"🧃"},
  {w:"burgers",ipa:"/ˈbɜːɡəz/",vi:"bánh mì kẹp thịt",vp:"bơ-gơ-z",e:"🍔"},
  {w:"milk tea",ipa:"/mɪlk tiː/",vi:"trà sữa",vp:"miu-k ti",e:"🧋"},
  {w:"pizza",ipa:"/ˈpiːtsə/",vi:"bánh pizza",vp:"pít-xơ",e:"🍕"},
  {w:"festival",ipa:"/ˈfestɪvl/",vi:"lễ hội",vp:"phe-xti-vồ",e:"🎊",st:1}],
 pat:[["What will you do on Teachers' Day?","We'll sing songs for our teachers."],["What food will you have at the party?","We'll have pizza."],["What drinks will you have at the party?","We'll have milk tea."]]},

{n:14,t:"Staying healthy",vi:"Giữ gìn sức khoẻ",th:"family",e:"💪",
 comp:["Hỏi và trả lời về cách giữ sức khoẻ","Hỏi và trả lời về mức độ thường xuyên"],
 focus:{label:"Nhịp câu",items:["Does she eat healthy food?","Is your brother a strong swimmer?"]},
 words:[
  {w:"do morning exercise",ipa:"/duː ˈmɔːnɪŋ ˈeksəsaɪz/",vi:"tập thể dục buổi sáng",vp:"đu mo-ning ec-xơ-xai-z",e:"🤸"},
  {w:"do yoga",ipa:"/duː ˈjəʊɡə/",vi:"tập yoga",vp:"đu dâu-gơ",e:"🧘"},
  {w:"drink fresh juice",ipa:"/drɪŋk freʃ dʒuːs/",vi:"uống nước ép tươi",vp:"đring-k phrét giu-s",e:"🧃"},
  {w:"eat healthy food",ipa:"/iːt ˈhelθi fuːd/",vi:"ăn đồ ăn lành mạnh",vp:"i-t heo-thi phu-đ",e:"🥗"},
  {w:"eat vegetables",ipa:"/iːt ˈvedʒtəblz/",vi:"ăn rau",vp:"i-t ve-giơ-tơ-bồ-z",e:"🥦"},
  {w:"play sports",ipa:"/pleɪ spɔːts/",vi:"chơi thể thao",vp:"plêi xpo-t-s",e:"⚽"},
  {w:"every day",ipa:"/ˈevri deɪ/",vi:"hằng ngày",vp:"ev-ri đêi",e:"📅"},
  {w:"once a week",ipa:"/wʌns ə wiːk/",vi:"một lần một tuần",vp:"oăn-s ơ uých",e:"1️⃣"},
  {w:"twice a week",ipa:"/twaɪs ə wiːk/",vi:"hai lần một tuần",vp:"tuai-s ơ uých",e:"2️⃣"},
  {w:"three times a week",ipa:"/θriː taɪmz ə wiːk/",vi:"ba lần một tuần",vp:"thri tai-m-z ơ uých",e:"3️⃣"},
  {w:"healthy",ipa:"/ˈhelθi/",vi:"khoẻ mạnh",vp:"heo-thi",e:"💪",st:1},
  {w:"exercise",ipa:"/ˈeksəsaɪz/",vi:"bài tập thể dục",vp:"ec-xơ-xai-z",e:"🏋️",st:1}],
 pat:[["How does she stay healthy?","She does morning exercise every day."],["How often does he play sports?","He plays sports three times a week."],["How does he stay healthy?","He eats healthy food."]]},

{n:15,t:"Our health",vi:"Sức khoẻ của chúng em",th:"family",e:"🤒",
 comp:["Hỏi và trả lời về vấn đề sức khoẻ thường gặp","Đưa ra lời khuyên"],
 focus:{label:"Nhịp câu",items:["What's the matter?","What should I do?"]},
 words:[
  {w:"headache",ipa:"/ˈhedeɪk/",vi:"đau đầu",vp:"hé-đêi-k",e:"🤕",st:1},
  {w:"sore throat",ipa:"/sɔː θrəʊt/",vi:"đau họng",vp:"xo thrâu-t",e:"😷"},
  {w:"stomach ache",ipa:"/ˈstʌmək eɪk/",vi:"đau bụng",vp:"xta-mợc êi-k",e:"🤢"},
  {w:"toothache",ipa:"/ˈtuːθeɪk/",vi:"đau răng",vp:"tu-th-êi-k",e:"🦷",st:1},
  {w:"drink warm water",ipa:"/drɪŋk wɔːm ˈwɔːtə/",vi:"uống nước ấm",vp:"đring-k uô-m uô-tơ",e:"🥛"},
  {w:"go to the dentist",ipa:"/ɡəʊ tə ðə ˈdentɪst/",vi:"đi khám răng",vp:"gâu tu đờ đen-tịt",e:"🪥"},
  {w:"have a rest",ipa:"/hæv ə rest/",vi:"nghỉ ngơi",vp:"heo ơ rét-t",e:"🛌"},
  {w:"take some medicine",ipa:"/teɪk sʌm ˈmedsn/",vi:"uống thuốc",vp:"têi-k xăm mét-xừn",e:"🥄"},
  {w:"medicine",ipa:"/ˈmedsn/",vi:"thuốc",vp:"mét-xừn",e:"💊",st:1}],
 pat:[["What's the matter?","I have a toothache."],["What should I do?","You should go to the dentist."],["What's the matter?","I have a headache."]]},

{n:16,t:"Seasons and the weather",vi:"Mùa và thời tiết",th:"world",e:"🍂",
 comp:["Hỏi và trả lời về thời tiết các mùa","Hỏi và trả lời về trang phục theo mùa"],
 focus:{label:"Ngữ điệu",items:["It's cloudy in autumn. ↘","I wear jeans in winter. ↘"]},
 words:[
  {w:"spring",ipa:"/sprɪŋ/",vi:"mùa xuân",vp:"xpring",e:"🌸"},
  {w:"summer",ipa:"/ˈsʌmə/",vi:"mùa hè",vp:"xa-mơ",e:"☀️",st:1},
  {w:"autumn",ipa:"/ˈɔːtəm/",vi:"mùa thu",vp:"ô-từm",e:"🍂",st:1},
  {w:"winter",ipa:"/ˈwɪntə/",vi:"mùa đông",vp:"uin-tơ",e:"❄️",st:1},
  {w:"cold",ipa:"/kəʊld/",vi:"lạnh",vp:"câu-lđ",e:"🥶"},
  {w:"cool",ipa:"/kuːl/",vi:"mát mẻ",vp:"cu-l",e:"🍃"},
  {w:"hot",ipa:"/hɒt/",vi:"nóng",vp:"hót",e:"🥵"},
  {w:"warm",ipa:"/wɔːm/",vi:"ấm áp",vp:"uô-m",e:"🌤️"},
  {w:"blouse",ipa:"/blaʊz/",vi:"áo cánh",vp:"blao-z",e:"👚"},
  {w:"jeans",ipa:"/dʒiːnz/",vi:"quần bò",vp:"gin-z",e:"👖"},
  {w:"jumper",ipa:"/ˈdʒʌmpə/",vi:"áo len dài tay",vp:"giăm-pơ",e:"🧥",st:1},
  {w:"trousers",ipa:"/ˈtraʊzəz/",vi:"quần dài",vp:"trao-zơ-z",e:"👖",st:1}],
 pat:[["How's the weather in Ha Noi in autumn?","It's cloudy in autumn."],["What do you usually wear in winter?","I wear jeans in winter."],["How's the weather in Ha Noi in summer?","It's hot in summer."]]},

{n:17,t:"Stories for children",vi:"Truyện cho thiếu nhi",th:"world",e:"📖",
 comp:["Hỏi và trả lời về nhân vật trong truyện","Hỏi và trả lời về việc nhân vật đã làm"],
 focus:{label:"Ngữ điệu",items:["Is this your storybook? ↗","Are you reading a story? ↗"]},
 words:[
  {w:"ant",ipa:"/ænt/",vi:"con kiến",vp:"en-t",e:"🐜"},
  {w:"crow",ipa:"/krəʊ/",vi:"con quạ",vp:"crâu",e:"🐦‍⬛"},
  {w:"dwarfs",ipa:"/dwɔːfs/",vi:"các chú lùn",vp:"đuô-phs",e:"🧙"},
  {w:"fox",ipa:"/fɒks/",vi:"con cáo",vp:"phóc-s",e:"🦊"},
  {w:"grasshopper",ipa:"/ˈɡrɑːshɒpə/",vi:"con châu chấu",vp:"grá-x-hóp-pơ",e:"🦗",st:1},
  {w:"hare",ipa:"/heə/",vi:"con thỏ rừng",vp:"he-ơ",e:"🐇"},
  {w:"Snow White",ipa:"/snəʊ waɪt/",vi:"Bạch Tuyết",vp:"xnâu oai-t",e:"👸"},
  {w:"tortoise",ipa:"/ˈtɔːtəs/",vi:"con rùa",vp:"to-tợt",e:"🐢",st:1},
  {w:"cook well",ipa:"/kʊk wel/",vi:"nấu ăn giỏi",vp:"cúc oeo",e:"👨‍🍳"},
  {w:"run fast",ipa:"/rʌn fɑːst/",vi:"chạy nhanh",vp:"răn phá-x-t",e:"🏃"},
  {w:"sing beautifully",ipa:"/sɪŋ ˈbjuːtɪfli/",vi:"hát hay",vp:"xing biu-ti-phli",e:"🎶"},
  {w:"work hard",ipa:"/wɜːk hɑːd/",vi:"chăm chỉ",vp:"uơ-c há-đ",e:"💪"}],
 pat:[["Who are the main characters in the story?","They're Snow White and the dwarfs."],["Is this your storybook?","Yes, it is."],["How did the tortoise win the race?","He worked hard."]]},

{n:18,t:"Means of transport",vi:"Phương tiện đi lại",th:"world",e:"🚌",
 comp:["Hỏi và trả lời về nơi muốn đến thăm","Hỏi và trả lời về phương tiện đi lại"],
 focus:{label:"Ngữ điệu",items:["Is it time for a trip? ↗","Is it far from here? ↗"]},
 words:[
  {w:"Dragon Bridge",ipa:"/ˈdræɡən brɪdʒ/",vi:"cầu Rồng",vp:"đre-gừn brít",e:"🌉"},
  {w:"Ha Noi Opera House",ipa:"/hɑː nɔɪ ˈɒprə haʊs/",vi:"Nhà hát Lớn Hà Nội",vp:"ha nôi óp-rơ hao-s",e:"🎭"},
  {w:"Ho Chi Minh City Museum",ipa:"/həʊ tʃiː mɪn ˈsɪti mjuˈziːəm/",vi:"Bảo tàng TP. Hồ Chí Minh",vp:"hô chi min xi-ti miu-zi-ừm",e:"🏙️"},
  {w:"Ngo Mon Square",ipa:"/ŋɔ mɔn skweə/",vi:"quảng trường Ngọ Môn",vp:"ngọ môn xquê-ơ",e:"🏯"},
  {w:"by bicycle",ipa:"/baɪ ˈbaɪsɪkl/",vi:"bằng xe đạp",vp:"bai bai-xi-cồ",e:"🚴"},
  {w:"by bus",ipa:"/baɪ bʌs/",vi:"bằng xe buýt",vp:"bai bát",e:"🚌"},
  {w:"by taxi",ipa:"/baɪ ˈtæksi/",vi:"bằng taxi",vp:"bai tec-xi",e:"🚕"},
  {w:"on foot",ipa:"/ɒn fʊt/",vi:"đi bộ",vp:"on phút",e:"🦶"},
  {w:"bicycle",ipa:"/ˈbaɪsɪkl/",vi:"xe đạp",vp:"bai-xi-cồ",e:"🚲",st:1},
  {w:"museum",ipa:"/mjuˈziːəm/",vi:"bảo tàng",vp:"miu-zi-ừm",e:"🏛️",st:2}],
 pat:[["Where do you want to visit?","I want to visit Dragon Bridge."],["How can I get to Ngo Mon Square?","You can get there by taxi."],["Is it far from here?","No, it isn't."]]},

{n:19,t:"Places of interest",vi:"Những nơi thú vị",th:"world",e:"🏞️",
 comp:["Hỏi và trả lời về cảm nghĩ về một nơi","Hỏi và trả lời về khoảng cách"],
 focus:{label:"Ngữ điệu",items:["What do you think of Ba Na Hills? ↘","How far is it from Tay Ninh to Can Tho? ↘"]},
 words:[
  {w:"beautiful",ipa:"/ˈbjuːtɪfl/",vi:"đẹp",vp:"biu-ti-phồ",e:"🌸",st:1},
  {w:"exciting",ipa:"/ɪkˈsaɪtɪŋ/",vi:"hào hứng, hấp dẫn",vp:"ích-xai-ting",e:"🎉",st:2},
  {w:"fantastic",ipa:"/fænˈtæstɪk/",vi:"tuyệt vời",vp:"phen-tá-x-tíc",e:"🌟",st:2},
  {w:"peaceful",ipa:"/ˈpiːsfl/",vi:"yên bình",vp:"pi-x-phồ",e:"🕊️",st:1},
  {w:"kilometre",ipa:"/kɪˈlɒmɪtə/",vi:"ki-lô-mét",vp:"ki-lo-mi-tơ",e:"📏",st:2}],
 pat:[["What do you think of Ba Na Hills?","I think it's fantastic."],["How far is it from Tay Ninh to Can Tho?","It's about 129 kilometres."],["What do you think of Phu Quoc Island?","I think it's peaceful."]]},

{n:20,t:"Our summer holidays",vi:"Kì nghỉ hè của chúng em",th:"world",e:"🏝️",
 comp:["Hỏi và trả lời về nơi sẽ đến thăm hè này","Hỏi và trả lời về việc sẽ làm hè này"],
 focus:{label:"Ngữ điệu",items:["Where are you going to visit this summer? ↘","What are you going to do this summer? ↘"]},
 words:[
  {w:"Dam Sen Aquarium",ipa:"/dɑːm sen əˈkweəriəm/",vi:"thuỷ cung Đầm Sen",vp:"đầm sen ơ-quê-ri-ừm",e:"🐠"},
  {w:"Huong River",ipa:"/hɜːŋ ˈrɪvə/",vi:"sông Hương",vp:"hương ri-vơ",e:"🏞️"},
  {w:"Phong Nha Cave",ipa:"/fɒŋ njaː keɪv/",vi:"động Phong Nha",vp:"phong nha kêi-v",e:"⛰️"},
  {w:"Phu Quoc Island",ipa:"/fuː kwɒk ˈaɪlənd/",vi:"đảo Phú Quốc",vp:"phu quốc ai-lừn-đ",e:"🌴"},
  {w:"go camping",ipa:"/ɡəʊ ˈkæmpɪŋ/",vi:"đi cắm trại",vp:"gâu kem-ping",e:"⛺"},
  {w:"join a music club",ipa:"/dʒɔɪn ə ˈmjuːzɪk klʌb/",vi:"tham gia câu lạc bộ âm nhạc",vp:"gioi-n ơ miu-zic clắp",e:"🎵"},
  {w:"practise swimming",ipa:"/ˈpræktɪs ˈswɪmɪŋ/",vi:"luyện bơi",vp:"prếc-tịt xuim-ming",e:"🏊"},
  {w:"visit an eco-farm",ipa:"/ˈvɪzɪt ən ˈiːkəʊ fɑːm/",vi:"thăm nông trại sinh thái",vp:"vi-zịt ơn i-câu pha-m",e:"🌱"},
  {w:"island",ipa:"/ˈaɪlənd/",vi:"hòn đảo",vp:"ai-lừn-đ",e:"🏝️",st:1},
  {w:"cave",ipa:"/keɪv/",vi:"hang động",vp:"kêi-v",e:"🕳️"}],
 pat:[["Where are you going to visit this summer?","I'm going to visit Phu Quoc Island."],["What are you going to do this summer?","I'm going to practise swimming."],["Where are you going to visit this summer?","I'm going to visit Phong Nha Cave."]]}
];

const G5_GROUPS = [
 {label:"ME AND MY FRIENDS",vi:"Em và bạn bè",icon:"🧑‍🤝‍🧑",units:[1,2,3,4,5]},
 {label:"ME AND MY SCHOOL",vi:"Em và trường học",icon:"🏫",units:[6,7,8,9,10]},
 {label:"ME AND MY FAMILY",vi:"Em và gia đình",icon:"👨‍👩‍👧",units:[11,12,13,14,15]},
 {label:"ME AND THE WORLD AROUND",vi:"Em và thế giới quanh em",icon:"🌏",units:[16,17,18,19,20]}
];

Object.assign(TRANS, {
/* --- câu trả lời ngắn: dùng bản dịch trung tính để đúng ở mọi lớp --- */
"OK.":"Vâng ạ.",
"Yes, I do.":"Có, đúng vậy.",
"No, I don't.":"Không, không phải.",
"Yes, I can.":"Có, mình làm được.",
"No, I can't.":"Không, mình không làm được.",
/* --- lớp 5 --- */
"Can you tell me about yourself?":"Bạn kể về bản thân mình được không?",
"I'm Mai. I'm ten years old.":"Mình là Mai. Mình mười tuổi.",
"What's your favourite animal?":"Con vật bạn thích nhất là gì?",
"It's a dolphin.":"Đó là cá heo.",
"I live in the countryside.":"Mình sống ở vùng quê.",
"What's your favourite sport?":"Môn thể thao con thích nhất là gì?",
"It's table tennis.":"Đó là bóng bàn.",
"Do you live in this tower?":"Bạn sống ở toà tháp này à?",
"Do you live in that flat?":"Bạn sống ở căn hộ kia à?",
"What's your address?":"Địa chỉ nhà bạn là gì?",
"It's 116 Nguyen Trai Street.":"Số 116 phố Nguyễn Trãi.",
"What nationality is he?":"Bạn ấy mang quốc tịch nào?",
"He's Japanese.":"Bạn ấy là người Nhật.",
"What's she like?":"Bạn ấy là người thế nào?",
"She's friendly and helpful.":"Bạn ấy thân thiện và hay giúp đỡ.",
"What nationality is she?":"Bạn ấy mang quốc tịch nào?",
"She's Australian.":"Bạn ấy là người Úc.",
"What do you like doing in your free time?":"Lúc rảnh bạn thích làm gì?",
"I like playing the violin.":"Mình thích chơi vĩ cầm.",
"What do you do at the weekend?":"Cuối tuần bạn làm gì?",
"I usually water the flowers.":"Mình thường tưới hoa.",
"I like surfing the Internet.":"Mình thích lướt mạng.",
"What would you like to be in the future?":"Sau này bạn muốn làm nghề gì?",
"I'd like to be a writer.":"Mình muốn làm nhà văn.",
"Why would you like to be a writer?":"Vì sao bạn muốn làm nhà văn?",
"Because I'd like to write stories.":"Vì mình muốn viết truyện.",
"I'd like to be a firefighter.":"Mình muốn làm lính cứu hoả.",
"Where's the art room?":"Phòng Mĩ thuật ở đâu?",
"It's on the second floor.":"Nó ở tầng hai.",
"Could you tell me the way to the computer room, please?":"Bạn chỉ giúp mình đường đến phòng máy tính với?",
"Go upstairs and go past the library.":"Lên gác rồi đi qua thư viện.",
"Where's the library?":"Thư viện ở đâu?",
"It's on the ground floor.":"Nó ở tầng trệt.",
"What school activity does he like?":"Bạn ấy thích hoạt động nào ở trường?",
"He likes reading books.":"Bạn ấy thích đọc sách.",
"Why does he like reading books?":"Vì sao bạn ấy thích đọc sách?",
"Because he thinks it's interesting.":"Vì bạn ấy thấy nó thú vị.",
"What school activity does she like?":"Bạn ấy thích hoạt động nào ở trường?",
"She likes doing projects.":"Bạn ấy thích làm dự án.",
"Where are the crayons?":"Những cây bút sáp ở đâu?",
"They're above the desk.":"Chúng ở phía trên bàn học.",
"Whose glue stick is this?":"Hồ dán này của ai?",
"It's Mai's.":"Của bạn Mai.",
"Where's the set square?":"Cái ê ke ở đâu?",
"It's under the book.":"Nó ở dưới quyển sách.",
"Were you at the funfair yesterday?":"Hôm qua các bạn có ở khu vui chơi không?",
"Yes, we were.":"Có, chúng mình có ở đó.",
"What did you do yesterday?":"Hôm qua các bạn làm gì?",
"We watched the fish at the aquarium.":"Chúng mình ngắm cá ở thuỷ cung.",
"Were you at the theatre yesterday?":"Hôm qua các bạn có ở nhà hát không?",
"No, we weren't.":"Không, chúng mình không ở đó.",
"Did they go to Ba Na Hills?":"Các bạn ấy có đi Bà Nà Hills không?",
"Yes, they did.":"Có, các bạn ấy có đi.",
"What did they do there?":"Ở đó các bạn ấy làm gì?",
"They planted trees.":"Các bạn ấy trồng cây.",
"Did they go to Hoan Kiem Lake?":"Các bạn ấy có đi hồ Hoàn Kiếm không?",
"No, they didn't.":"Không, các bạn ấy không đi.",
"Did you go to Ha Long Bay?":"Bạn có đi vịnh Hạ Long không?",
"Yes, I did. I took a boat trip around the bay.":"Có. Mình đi thuyền quanh vịnh.",
"What did your family do in Da Nang?":"Ở Đà Nẵng gia đình bạn làm gì?",
"We walked on the beach.":"Chúng mình đi dạo trên bãi biển.",
"Did you eat seafood?":"Bạn có ăn hải sản không?",
"Yes, I did.":"Có, mình có ăn.",
"Will you make banh chung for Tet?":"Tết này bạn có gói bánh chưng không?",
"Yes, I will.":"Có, mình sẽ gói.",
"Where will you go at Tet?":"Tết này bạn sẽ đi đâu?",
"I'll go to my grandparents' house.":"Mình sẽ về nhà ông bà.",
"Will you buy roses for Tet?":"Tết này bạn có mua hoa hồng không?",
"No, I won't. I'll buy peach blossoms.":"Không. Mình sẽ mua hoa đào.",
"What will you do on Teachers' Day?":"Ngày Nhà giáo các bạn sẽ làm gì?",
"We'll sing songs for our teachers.":"Chúng mình sẽ hát tặng thầy cô.",
"What food will you have at the party?":"Trong bữa tiệc các bạn sẽ ăn gì?",
"We'll have pizza.":"Chúng mình sẽ ăn pizza.",
"What drinks will you have at the party?":"Trong bữa tiệc các bạn sẽ uống gì?",
"We'll have milk tea.":"Chúng mình sẽ uống trà sữa.",
"How does she stay healthy?":"Cô ấy giữ sức khoẻ bằng cách nào?",
"She does morning exercise every day.":"Cô ấy tập thể dục buổi sáng hằng ngày.",
"How often does he play sports?":"Bạn ấy chơi thể thao bao lâu một lần?",
"He plays sports three times a week.":"Bạn ấy chơi thể thao ba lần một tuần.",
"How does he stay healthy?":"Bạn ấy giữ sức khoẻ bằng cách nào?",
"He eats healthy food.":"Bạn ấy ăn đồ ăn lành mạnh.",
"What's the matter?":"Bạn bị làm sao thế?",
"I have a toothache.":"Mình bị đau răng.",
"What should I do?":"Mình nên làm gì?",
"You should go to the dentist.":"Bạn nên đi khám răng.",
"I have a headache.":"Mình bị đau đầu.",
"How's the weather in Ha Noi in autumn?":"Mùa thu ở Hà Nội thời tiết thế nào?",
"It's cloudy in autumn.":"Mùa thu trời nhiều mây.",
"What do you usually wear in winter?":"Mùa đông bạn thường mặc gì?",
"I wear jeans in winter.":"Mùa đông mình mặc quần bò.",
"How's the weather in Ha Noi in summer?":"Mùa hè ở Hà Nội thời tiết thế nào?",
"It's hot in summer.":"Mùa hè trời nóng.",
"Who are the main characters in the story?":"Nhân vật chính trong truyện là ai?",
"They're Snow White and the dwarfs.":"Đó là Bạch Tuyết và các chú lùn.",
"Is this your storybook?":"Đây là quyển truyện của bạn phải không?",
"How did the tortoise win the race?":"Rùa đã thắng cuộc đua bằng cách nào?",
"He worked hard.":"Cậu ấy đã rất chăm chỉ.",
"Where do you want to visit?":"Bạn muốn đến thăm nơi nào?",
"I want to visit Dragon Bridge.":"Mình muốn đến cầu Rồng.",
"How can I get to Ngo Mon Square?":"Làm sao để đến quảng trường Ngọ Môn?",
"You can get there by taxi.":"Bạn có thể đi taxi.",
"Is it far from here?":"Từ đây đến đó có xa không?",
"What do you think of Ba Na Hills?":"Bạn thấy Bà Nà Hills thế nào?",
"I think it's fantastic.":"Mình thấy nơi đó tuyệt vời.",
"How far is it from Tay Ninh to Can Tho?":"Từ Tây Ninh đến Cần Thơ bao xa?",
"It's about 129 kilometres.":"Khoảng 129 ki-lô-mét.",
"What do you think of Phu Quoc Island?":"Bạn thấy đảo Phú Quốc thế nào?",
"I think it's peaceful.":"Mình thấy nơi đó yên bình.",
"Where are you going to visit this summer?":"Hè này bạn sẽ đi thăm nơi nào?",
"I'm going to visit Phu Quoc Island.":"Mình sẽ đi đảo Phú Quốc.",
"What are you going to do this summer?":"Hè này bạn sẽ làm gì?",
"I'm going to practise swimming.":"Mình sẽ luyện bơi.",
"I'm going to visit Phong Nha Cave.":"Mình sẽ đi động Phong Nha."
});

/* =====================================================================
   PHẦN NÂNG CAO — từ vựng MỞ RỘNG ngoài SGK, gom theo chủ đề
   Lúc chạy, từ nào trùng với SGK của lớp đó sẽ tự bị loại.
   ===================================================================== */
const EXT = {
animals:[
 {w:"bear",ipa:"/beə/",vi:"con gấu",vp:"be-ơ",e:"🐻"},
 {w:"panda",ipa:"/ˈpændə/",vi:"gấu trúc",vp:"pen-đơ",e:"🐼",st:1},
 {w:"penguin",ipa:"/ˈpeŋɡwɪn/",vi:"chim cánh cụt",vp:"pen-guin",e:"🐧",st:1},
 {w:"snake",ipa:"/sneɪk/",vi:"con rắn",vp:"xnêi-k",e:"🐍"},
 {w:"frog",ipa:"/frɒɡ/",vi:"con ếch",vp:"phróc",e:"🐸"},
 {w:"owl",ipa:"/aʊl/",vi:"con cú",vp:"ao-l",e:"🦉"},
 {w:"whale",ipa:"/weɪl/",vi:"cá voi",vp:"uêi-l",e:"🐋"},
 {w:"crab",ipa:"/kræb/",vi:"con cua",vp:"cre-b",e:"🦀"},
 {w:"butterfly",ipa:"/ˈbʌtəflaɪ/",vi:"con bướm",vp:"ba-tơ-phlai",e:"🦋",st:1},
 {w:"camel",ipa:"/ˈkæml/",vi:"lạc đà",vp:"ke-mồ",e:"🐫",st:1},
 {w:"bee",ipa:"/biː/",vi:"con ong",vp:"bi",e:"🐝"},
 {w:"squirrel",ipa:"/ˈskwɪrəl/",vi:"con sóc",vp:"xqui-rồ",e:"🐿️",st:1}],
food:[
 {w:"cheese",ipa:"/tʃiːz/",vi:"phô mai",vp:"chi-z",e:"🧀"},
 {w:"soup",ipa:"/suːp/",vi:"canh, súp",vp:"xup",e:"🥣"},
 {w:"candy",ipa:"/ˈkændi/",vi:"kẹo",vp:"ken-đi",e:"🍬",st:1},
 {w:"watermelon",ipa:"/ˈwɔːtəmelən/",vi:"dưa hấu",vp:"uô-tơ-me-lừn",e:"🍉",st:1},
 {w:"pineapple",ipa:"/ˈpaɪnæpl/",vi:"quả dứa",vp:"pai-náp-pồ",e:"🍍",st:1},
 {w:"corn",ipa:"/kɔːn/",vi:"ngô",vp:"co-n",e:"🌽"},
 {w:"honey",ipa:"/ˈhʌni/",vi:"mật ong",vp:"ha-ni",e:"🍯",st:1},
 {w:"salad",ipa:"/ˈsæləd/",vi:"rau trộn",vp:"xe-lợt",e:"🥗",st:1},
 {w:"sausage",ipa:"/ˈsɒsɪdʒ/",vi:"xúc xích",vp:"xó-xịch",e:"🌭",st:1},
 {w:"strawberry",ipa:"/ˈstrɔːbəri/",vi:"quả dâu",vp:"xtro-bơ-ri",e:"🍓",st:1},
 {w:"ice cream",ipa:"/ˈaɪs kriːm/",vi:"kem",vp:"ai-x cri-m",e:"🍦"},
 {w:"coconut",ipa:"/ˈkəʊkənʌt/",vi:"quả dừa",vp:"câu-cơ-nắt",e:"🥥",st:1}],
body:[
 {w:"knee",ipa:"/niː/",vi:"đầu gối",vp:"ni",e:"🦵"},
 {w:"elbow",ipa:"/ˈelbəʊ/",vi:"khuỷu tay",vp:"eo-bâu",e:"💪",st:1},
 {w:"shoulder",ipa:"/ˈʃəʊldə/",vi:"vai",vp:"sâu-đơ",e:"🙆",st:1},
 {w:"finger",ipa:"/ˈfɪŋɡə/",vi:"ngón tay",vp:"phing-gơ",e:"👆",st:1},
 {w:"toe",ipa:"/təʊ/",vi:"ngón chân",vp:"tâu",e:"🦶"},
 {w:"tooth",ipa:"/tuːθ/",vi:"cái răng",vp:"tu-th",e:"🦷"},
 {w:"tongue",ipa:"/tʌŋ/",vi:"cái lưỡi",vp:"tăng",e:"👅"},
 {w:"neck",ipa:"/nek/",vi:"cái cổ",vp:"néc",e:"🧣"},
 {w:"arm",ipa:"/ɑːm/",vi:"cánh tay",vp:"a-m",e:"💪"},
 {w:"leg",ipa:"/leɡ/",vi:"cái chân",vp:"lếch",e:"🦵"},
 {w:"chin",ipa:"/tʃɪn/",vi:"cằm",vp:"chi-n",e:"😀"},
 {w:"stomach",ipa:"/ˈstʌmək/",vi:"bụng",vp:"xta-mợc",e:"🍽️",st:1}],
school:[
 {w:"board",ipa:"/bɔːd/",vi:"bảng",vp:"bo-đ",e:"🪧"},
 {w:"chalk",ipa:"/tʃɔːk/",vi:"viên phấn",vp:"chóc",e:"🖍️"},
 {w:"globe",ipa:"/ɡləʊb/",vi:"quả địa cầu",vp:"glâu-b",e:"🌐"},
 {w:"dictionary",ipa:"/ˈdɪkʃənri/",vi:"từ điển",vp:"đích-sơ-nơ-ri",e:"📔",st:1},
 {w:"calculator",ipa:"/ˈkælkjuleɪtə/",vi:"máy tính bỏ túi",vp:"ken-kiu-lêi-tơ",e:"🧮",st:1},
 {w:"folder",ipa:"/ˈfəʊldə/",vi:"bìa kẹp hồ sơ",vp:"phâu-đơ",e:"📁",st:1},
 {w:"homework",ipa:"/ˈhəʊmwɜːk/",vi:"bài tập về nhà",vp:"hâu-m-uơ-c",e:"📝",st:1},
 {w:"marker",ipa:"/ˈmɑːkə/",vi:"bút lông",vp:"ma-cơ",e:"🖊️",st:1},
 {w:"scissors",ipa:"/ˈsɪzəz/",vi:"cái kéo",vp:"xi-zơ-z",e:"✂️",st:1},
 {w:"uniform",ipa:"/ˈjuːnɪfɔːm/",vi:"đồng phục",vp:"diu-ni-pho-m",e:"👔",st:1},
 {w:"bell",ipa:"/bel/",vi:"chuông trường",vp:"beo",e:"🔔"},
 {w:"corridor",ipa:"/ˈkɒrɪdɔː/",vi:"hành lang",vp:"có-ri-đo",e:"🚪",st:1}],
home:[
 {w:"sofa",ipa:"/ˈsəʊfə/",vi:"ghế sô pha",vp:"xâu-phơ",e:"🛋️",st:1},
 {w:"fridge",ipa:"/frɪdʒ/",vi:"tủ lạnh",vp:"phrít",e:"🧊"},
 {w:"wardrobe",ipa:"/ˈwɔːdrəʊb/",vi:"tủ quần áo",vp:"uô-đrâu-b",e:"🚪",st:1},
 {w:"mirror",ipa:"/ˈmɪrə/",vi:"cái gương",vp:"mi-rơ",e:"🪞",st:1},
 {w:"carpet",ipa:"/ˈkɑːpɪt/",vi:"tấm thảm",vp:"ca-pịt",e:"🧶",st:1},
 {w:"curtain",ipa:"/ˈkɜːtn/",vi:"rèm cửa",vp:"cơ-từn",e:"🪟",st:1},
 {w:"stairs",ipa:"/steəz/",vi:"cầu thang",vp:"xte-ơ-z",e:"🪜"},
 {w:"balcony",ipa:"/ˈbælkəni/",vi:"ban công",vp:"ben-cơ-ni",e:"🏠",st:1},
 {w:"garage",ipa:"/ˈɡærɑːʒ/",vi:"ga ra ô tô",vp:"ge-rát",e:"🚗",st:1},
 {w:"roof",ipa:"/ruːf/",vi:"mái nhà",vp:"ru-ph",e:"🏠"},
 {w:"pillow",ipa:"/ˈpɪləʊ/",vi:"cái gối",vp:"pi-lâu",e:"🛏️",st:1},
 {w:"clock",ipa:"/klɒk/",vi:"đồng hồ treo",vp:"clóc",e:"🕰️"}],
clothes:[
 {w:"cap",ipa:"/kæp/",vi:"mũ lưỡi trai",vp:"kép",e:"🧢"},
 {w:"scarf",ipa:"/skɑːf/",vi:"khăn quàng",vp:"xca-ph",e:"🧣"},
 {w:"gloves",ipa:"/ɡlʌvz/",vi:"găng tay",vp:"glá-v-z",e:"🧤"},
 {w:"socks",ipa:"/sɒks/",vi:"tất, vớ",vp:"xóc-s",e:"🧦"},
 {w:"boots",ipa:"/buːts/",vi:"giày bốt",vp:"bu-t-s",e:"🥾"},
 {w:"dress",ipa:"/dres/",vi:"váy liền",vp:"đrét",e:"👗"},
 {w:"coat",ipa:"/kəʊt/",vi:"áo khoác",vp:"câu-t",e:"🧥"},
 {w:"sandals",ipa:"/ˈsændlz/",vi:"dép quai hậu",vp:"xen-đồ-z",e:"👡",st:1},
 {w:"belt",ipa:"/belt/",vi:"thắt lưng",vp:"beo-t",e:"🎗️"},
 {w:"pyjamas",ipa:"/pəˈdʒɑːməz/",vi:"đồ ngủ",vp:"pơ-gia-mơ-z",e:"🩱",st:2},
 {w:"helmet",ipa:"/ˈhelmɪt/",vi:"mũ bảo hiểm",vp:"heo-mịt",e:"🪖",st:1},
 {w:"glasses",ipa:"/ˈɡlɑːsɪz/",vi:"kính mắt",vp:"gla-xịz",e:"👓",st:1}],
colours:[
 {w:"purple",ipa:"/ˈpɜːpl/",vi:"màu tím",vp:"pơ-pồ",e:"💜",st:1},
 {w:"grey",ipa:"/ɡreɪ/",vi:"màu xám",vp:"grêi",e:"🌫️"},
 {w:"pink",ipa:"/pɪŋk/",vi:"màu hồng",vp:"ping-k",e:"💗"},
 {w:"gold",ipa:"/ɡəʊld/",vi:"màu vàng kim",vp:"gâu-lđ",e:"🏅"},
 {w:"silver",ipa:"/ˈsɪlvə/",vi:"màu bạc",vp:"xiu-vơ",e:"⚪",st:1},
 {w:"dark",ipa:"/dɑːk/",vi:"(màu) đậm, tối",vp:"đá-c",e:"🌑"},
 {w:"light",ipa:"/laɪt/",vi:"(màu) nhạt, sáng",vp:"lai-t",e:"💡"},
 {w:"colourful",ipa:"/ˈkʌləfl/",vi:"nhiều màu sắc",vp:"ca-lơ-phồ",e:"🌈",st:1}],
family:[
 {w:"uncle",ipa:"/ˈʌŋkl/",vi:"chú, bác, cậu",vp:"ăng-cồ",e:"👨",st:1},
 {w:"aunt",ipa:"/ɑːnt/",vi:"cô, dì, bác gái",vp:"an-t",e:"👩"},
 {w:"cousin",ipa:"/ˈkʌzn/",vi:"anh chị em họ",vp:"ca-zừn",e:"🧑",st:1},
 {w:"grandfather",ipa:"/ˈɡrænfɑːðə/",vi:"ông",vp:"gren-pha-đơ",e:"👴",st:1},
 {w:"grandmother",ipa:"/ˈɡrænmʌðə/",vi:"bà",vp:"gren-ma-đơ",e:"👵",st:1},
 {w:"parents",ipa:"/ˈpeərənts/",vi:"bố mẹ",vp:"pe-rừn-t-s",e:"👨‍👩‍👦",st:1},
 {w:"baby",ipa:"/ˈbeɪbi/",vi:"em bé",vp:"bêi-bi",e:"👶",st:1},
 {w:"twins",ipa:"/twɪnz/",vi:"cặp sinh đôi",vp:"tuin-z",e:"👯"},
 {w:"neighbour",ipa:"/ˈneɪbə/",vi:"hàng xóm",vp:"nêi-bơ",e:"🏘️",st:1}],
jobs:[
 {w:"pilot",ipa:"/ˈpaɪlət/",vi:"phi công",vp:"pai-lợt",e:"👨‍✈️",st:1},
 {w:"engineer",ipa:"/ˌendʒɪˈnɪə/",vi:"kĩ sư",vp:"en-gi-ni-ơ",e:"👷",st:3},
 {w:"chef",ipa:"/ʃef/",vi:"bếp trưởng",vp:"séph",e:"👨‍🍳"},
 {w:"vet",ipa:"/vet/",vi:"bác sĩ thú y",vp:"vét",e:"🐕"},
 {w:"artist",ipa:"/ˈɑːtɪst/",vi:"nghệ sĩ",vp:"a-tịt",e:"🎨",st:1},
 {w:"scientist",ipa:"/ˈsaɪəntɪst/",vi:"nhà khoa học",vp:"xai-ừn-tịt",e:"🔬",st:1},
 {w:"soldier",ipa:"/ˈsəʊldʒə/",vi:"người lính",vp:"xâu-giơ",e:"🪖",st:1},
 {w:"mechanic",ipa:"/məˈkænɪk/",vi:"thợ máy",vp:"mơ-ke-níc",e:"🔧",st:2},
 {w:"shopkeeper",ipa:"/ˈʃɒpkiːpə/",vi:"chủ cửa hàng",vp:"sóp-ki-pơ",e:"🏪",st:1},
 {w:"librarian",ipa:"/laɪˈbreəriən/",vi:"thủ thư",vp:"lai-bre-ri-ừn",e:"📚",st:2}],
sports:[
 {w:"karate",ipa:"/kəˈrɑːti/",vi:"môn ka-ra-tê",vp:"cơ-ra-ti",e:"🥋",st:2},
 {w:"baseball",ipa:"/ˈbeɪsbɔːl/",vi:"bóng chày",vp:"bêi-x-bôl",e:"⚾",st:1},
 {w:"boxing",ipa:"/ˈbɒksɪŋ/",vi:"quyền anh",vp:"bóc-xing",e:"🥊",st:1},
 {w:"hockey",ipa:"/ˈhɒki/",vi:"khúc côn cầu",vp:"hó-ki",e:"🏒",st:1},
 {w:"jogging",ipa:"/ˈdʒɒɡɪŋ/",vi:"chạy bộ",vp:"gióc-ghing",e:"🏃",st:1},
 {w:"climbing",ipa:"/ˈklaɪmɪŋ/",vi:"leo núi",vp:"clai-ming",e:"🧗",st:1},
 {w:"surfing",ipa:"/ˈsɜːfɪŋ/",vi:"lướt sóng",vp:"xơ-phing",e:"🏄",st:1},
 {w:"team",ipa:"/tiːm/",vi:"đội",vp:"ti-m",e:"👥"},
 {w:"winner",ipa:"/ˈwɪnə/",vi:"người thắng",vp:"ui-nơ",e:"🏆",st:1},
 {w:"medal",ipa:"/ˈmedl/",vi:"huy chương",vp:"me-đồ",e:"🥇",st:1}],
transport:[
 {w:"motorbike",ipa:"/ˈməʊtəbaɪk/",vi:"xe máy",vp:"mâu-tơ-bai-k",e:"🏍️",st:1},
 {w:"helicopter",ipa:"/ˈhelɪkɒptə/",vi:"trực thăng",vp:"he-li-cóp-tơ",e:"🚁",st:1},
 {w:"boat",ipa:"/bəʊt/",vi:"con thuyền",vp:"bâu-t",e:"🛶"},
 {w:"subway",ipa:"/ˈsʌbweɪ/",vi:"tàu điện ngầm",vp:"xáp-uêi",e:"🚇",st:1},
 {w:"tram",ipa:"/træm/",vi:"tàu điện",vp:"trem",e:"🚋"},
 {w:"ambulance",ipa:"/ˈæmbjələns/",vi:"xe cứu thương",vp:"em-biu-lừn-s",e:"🚑",st:1},
 {w:"ferry",ipa:"/ˈferi/",vi:"phà",vp:"phe-ri",e:"⛴️",st:1},
 {w:"rocket",ipa:"/ˈrɒkɪt/",vi:"tên lửa",vp:"ró-kịt",e:"🚀",st:1},
 {w:"scooter",ipa:"/ˈskuːtə/",vi:"xe tay ga",vp:"xcu-tơ",e:"🛵",st:1}],
nature:[
 {w:"forest",ipa:"/ˈfɒrɪst/",vi:"khu rừng",vp:"phó-rịt",e:"🌲",st:1},
 {w:"hill",ipa:"/hɪl/",vi:"ngọn đồi",vp:"hiu",e:"⛰️"},
 {w:"desert",ipa:"/ˈdezət/",vi:"sa mạc",vp:"đe-zợt",e:"🏜️",st:1},
 {w:"waterfall",ipa:"/ˈwɔːtəfɔːl/",vi:"thác nước",vp:"uô-tơ-phôl",e:"💦",st:1},
 {w:"cloud",ipa:"/klaʊd/",vi:"đám mây",vp:"clao-đ",e:"☁️"},
 {w:"star",ipa:"/stɑː/",vi:"ngôi sao",vp:"xta",e:"⭐"},
 {w:"moon",ipa:"/muːn/",vi:"mặt trăng",vp:"mu-n",e:"🌙"},
 {w:"grass",ipa:"/ɡrɑːs/",vi:"cỏ",vp:"gra-x",e:"🌱"},
 {w:"rock",ipa:"/rɒk/",vi:"tảng đá",vp:"róc",e:"🪨"},
 {w:"seed",ipa:"/siːd/",vi:"hạt giống",vp:"xi-đ",e:"🌰"}],
weather:[
 {w:"storm",ipa:"/stɔːm/",vi:"cơn bão",vp:"xto-m",e:"⛈️"},
 {w:"snow",ipa:"/snəʊ/",vi:"tuyết",vp:"xnâu",e:"❄️"},
 {w:"fog",ipa:"/fɒɡ/",vi:"sương mù",vp:"phóc",e:"🌫️"},
 {w:"thunder",ipa:"/ˈθʌndə/",vi:"sấm",vp:"thăn-đơ",e:"🌩️",st:1},
 {w:"lightning",ipa:"/ˈlaɪtnɪŋ/",vi:"chớp",vp:"lai-t-ning",e:"⚡",st:1},
 {w:"wind",ipa:"/wɪnd/",vi:"gió",vp:"uin-đ",e:"🌬️"},
 {w:"umbrella",ipa:"/ʌmˈbrelə/",vi:"cái ô",vp:"ăm-bre-lơ",e:"☂️",st:2},
 {w:"season",ipa:"/ˈsiːzn/",vi:"mùa",vp:"xi-zừn",e:"🍂",st:1}],
time:[
 {w:"minute",ipa:"/ˈmɪnɪt/",vi:"phút",vp:"mi-nịt",e:"⏱️",st:1},
 {w:"hour",ipa:"/ˈaʊə/",vi:"giờ",vp:"ao-ơ",e:"🕐",st:1},
 {w:"week",ipa:"/wiːk/",vi:"tuần",vp:"uých",e:"📅"},
 {w:"month",ipa:"/mʌnθ/",vi:"tháng",vp:"măn-th",e:"🗓️"},
 {w:"year",ipa:"/jɪə/",vi:"năm",vp:"di-ơ",e:"📆"},
 {w:"today",ipa:"/təˈdeɪ/",vi:"hôm nay",vp:"tu-đêi",e:"📍",st:2},
 {w:"tomorrow",ipa:"/təˈmɒrəʊ/",vi:"ngày mai",vp:"tu-mo-râu",e:"➡️",st:2},
 {w:"early",ipa:"/ˈɜːli/",vi:"sớm",vp:"ơ-li",e:"🌅",st:1},
 {w:"late",ipa:"/leɪt/",vi:"muộn",vp:"lêi-t",e:"🌙"},
 {w:"weekend",ipa:"/ˌwiːkˈend/",vi:"cuối tuần",vp:"uých-en-đ",e:"🎉",st:2}],
numbers:[
 {w:"thirty",ipa:"/ˈθɜːti/",vi:"số ba mươi (30)",vp:"thơ-ti",e:"3️⃣",st:1},
 {w:"forty",ipa:"/ˈfɔːti/",vi:"số bốn mươi (40)",vp:"pho-ti",e:"4️⃣",st:1},
 {w:"fifty",ipa:"/ˈfɪfti/",vi:"số năm mươi (50)",vp:"phíp-ti",e:"5️⃣",st:1},
 {w:"sixty",ipa:"/ˈsɪksti/",vi:"số sáu mươi (60)",vp:"xích-x-ti",e:"6️⃣",st:1},
 {w:"seventy",ipa:"/ˈsevnti/",vi:"số bảy mươi (70)",vp:"xe-vừn-ti",e:"7️⃣",st:1},
 {w:"eighty",ipa:"/ˈeɪti/",vi:"số tám mươi (80)",vp:"êi-ti",e:"8️⃣",st:1},
 {w:"ninety",ipa:"/ˈnaɪnti/",vi:"số chín mươi (90)",vp:"nai-n-ti",e:"9️⃣",st:1},
 {w:"hundred",ipa:"/ˈhʌndrəd/",vi:"số một trăm (100)",vp:"hăn-đrợt",e:"💯",st:1},
 {w:"first",ipa:"/fɜːst/",vi:"thứ nhất",vp:"phơ-x-t",e:"🥇"},
 {w:"second",ipa:"/ˈsekənd/",vi:"thứ hai",vp:"xe-cừn-đ",e:"🥈",st:1}],
feelings:[
 {w:"happy",ipa:"/ˈhæpi/",vi:"vui vẻ",vp:"he-pi",e:"😄",st:1},
 {w:"sad",ipa:"/sæd/",vi:"buồn",vp:"xét",e:"😢"},
 {w:"angry",ipa:"/ˈæŋɡri/",vi:"tức giận",vp:"eng-gri",e:"😠",st:1},
 {w:"tired",ipa:"/ˈtaɪəd/",vi:"mệt",vp:"tai-ợt",e:"😴",st:1},
 {w:"hungry",ipa:"/ˈhʌŋɡri/",vi:"đói",vp:"hăng-gri",e:"🍽️",st:1},
 {w:"thirsty",ipa:"/ˈθɜːsti/",vi:"khát",vp:"thơ-x-ti",e:"🥤",st:1},
 {w:"scared",ipa:"/skeəd/",vi:"sợ hãi",vp:"xke-ợt",e:"😨"},
 {w:"excited",ipa:"/ɪkˈsaɪtɪd/",vi:"hào hứng",vp:"ích-xai-tịt",e:"🤩",st:2},
 {w:"bored",ipa:"/bɔːd/",vi:"chán",vp:"bo-đ",e:"😐"},
 {w:"surprised",ipa:"/səˈpraɪzd/",vi:"ngạc nhiên",vp:"xơ-prai-zđ",e:"😲",st:2}],
places:[
 {w:"post office",ipa:"/ˈpəʊst ɒfɪs/",vi:"bưu điện",vp:"pâu-x-t ó-phịt",e:"📮"},
 {w:"supermarket",ipa:"/ˈsuːpəmɑːkɪt/",vi:"siêu thị",vp:"xu-pơ-ma-kịt",e:"🛒",st:1},
 {w:"bank",ipa:"/bæŋk/",vi:"ngân hàng",vp:"beng-k",e:"🏦"},
 {w:"airport",ipa:"/ˈeəpɔːt/",vi:"sân bay",vp:"e-ơ-po-t",e:"✈️",st:1},
 {w:"station",ipa:"/ˈsteɪʃn/",vi:"nhà ga",vp:"xtêi-sừn",e:"🚉",st:1},
 {w:"restaurant",ipa:"/ˈrestrɒnt/",vi:"nhà hàng",vp:"ré-xtơ-rong",e:"🍽️",st:1},
 {w:"pharmacy",ipa:"/ˈfɑːməsi/",vi:"hiệu thuốc",vp:"pha-mơ-xi",e:"💊",st:1},
 {w:"stadium",ipa:"/ˈsteɪdiəm/",vi:"sân vận động",vp:"xtêi-đi-ừm",e:"🏟️",st:1},
 {w:"temple",ipa:"/ˈtempl/",vi:"ngôi đền",vp:"tem-pồ",e:"🛕",st:1}],
activities:[
 {w:"jumping",ipa:"/ˈdʒʌmpɪŋ/",vi:"nhảy lên",vp:"giăm-ping",e:"🤾",st:1},
 {w:"laughing",ipa:"/ˈlɑːfɪŋ/",vi:"cười",vp:"la-phing",e:"😆",st:1},
 {w:"sleeping",ipa:"/ˈsliːpɪŋ/",vi:"ngủ",vp:"xli-ping",e:"😴",st:1},
 {w:"waiting",ipa:"/ˈweɪtɪŋ/",vi:"chờ đợi",vp:"uêi-ting",e:"⏳",st:1},
 {w:"helping",ipa:"/ˈhelpɪŋ/",vi:"giúp đỡ",vp:"heo-ping",e:"🤝",st:1},
 {w:"cleaning",ipa:"/ˈkliːnɪŋ/",vi:"dọn dẹp",vp:"cli-ning",e:"🧽",st:1},
 {w:"shopping",ipa:"/ˈʃɒpɪŋ/",vi:"mua sắm",vp:"sóp-ping",e:"🛍️",st:1},
 {w:"fishing",ipa:"/ˈfɪʃɪŋ/",vi:"câu cá",vp:"phi-sing",e:"🎣",st:1},
 {w:"cooking",ipa:"/ˈkʊkɪŋ/",vi:"nấu nướng",vp:"cúc-king",e:"🍳",st:1},
 {w:"reading",ipa:"/ˈriːdɪŋ/",vi:"đọc sách",vp:"ri-đing",e:"📖",st:1}],
toys:[
 {w:"doll",ipa:"/dɒl/",vi:"búp bê",vp:"đôl",e:"🪆"},
 {w:"robot",ipa:"/ˈrəʊbɒt/",vi:"người máy",vp:"râu-bót",e:"🤖",st:1},
 {w:"puzzle",ipa:"/ˈpʌzl/",vi:"trò xếp hình",vp:"pa-zồ",e:"🧩",st:1},
 {w:"balloon",ipa:"/bəˈluːn/",vi:"quả bóng bay",vp:"bơ-lu-n",e:"🎈",st:2},
 {w:"marbles",ipa:"/ˈmɑːblz/",vi:"viên bi",vp:"ma-bồ-z",e:"⚪",st:1},
 {w:"drum",ipa:"/drʌm/",vi:"cái trống",vp:"đrăm",e:"🥁"},
 {w:"blocks",ipa:"/blɒks/",vi:"khối xếp hình",vp:"blóc-s",e:"🧱"},
 {w:"board game",ipa:"/ˈbɔːd ɡeɪm/",vi:"trò chơi bàn cờ",vp:"bo-đ ghêi-m",e:"🎲"}],
travel:[
 {w:"suitcase",ipa:"/ˈsuːtkeɪs/",vi:"va li",vp:"xu-t-kêi-s",e:"🧳",st:1},
 {w:"ticket",ipa:"/ˈtɪkɪt/",vi:"vé",vp:"tí-kịt",e:"🎫",st:1},
 {w:"passport",ipa:"/ˈpɑːspɔːt/",vi:"hộ chiếu",vp:"pa-x-po-t",e:"🛂",st:1},
 {w:"map",ipa:"/mæp/",vi:"bản đồ",vp:"mép",e:"🗺️"},
 {w:"hotel",ipa:"/həʊˈtel/",vi:"khách sạn",vp:"hâu-teo",e:"🏨",st:2},
 {w:"camera",ipa:"/ˈkæmrə/",vi:"máy ảnh",vp:"kem-rơ",e:"📷",st:1},
 {w:"tourist",ipa:"/ˈtʊərɪst/",vi:"khách du lịch",vp:"tua-rịt",e:"🧑‍🦰",st:1},
 {w:"holiday",ipa:"/ˈhɒlədeɪ/",vi:"kì nghỉ",vp:"hó-lơ-đêi",e:"🏖️",st:1}]
};

/* chủ đề mở rộng cho từng lớp (lấy theo nội dung SGK của lớp đó) */
const EXT_GRADE = {
 1:["animals","food","toys","school","home","body","transport","colours"],
 2:["animals","food","nature","school","home","clothes","numbers","transport"],
 3:["colours","body","family","jobs","home","food","animals","toys","school","sports","activities"],
 4:["time","numbers","weather","places","jobs","clothes","transport","sports","food","activities","feelings"],
 5:["feelings","places","travel","weather","clothes","jobs","family","nature","time","activities","body"]
};

/* trình độ Cambridge tương ứng từng lớp (tham khảo phổ biến ở VN) */
const CAMB = {1:"Starters",2:"Starters",3:"Movers",4:"Movers",5:"Flyers"};

/* nhóm từ dễ nhầm — dùng cho trò "Chọn dạng đúng" */
const GRAM_SETS = [
 ["is","are","am","was","were"],
 ["do","does","did","don't","doesn't"],
 ["have","has","had"],
 ["can","can't","could"],
 ["will","won't","shall"],
 ["a","an","the","some"],
 ["this","that","these","those"],
 ["he","she","it","they"],
 ["my","your","his","her"],
 ["in","on","at","to"]
];
